- lua/null-ls/client.lua
See [this issue](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/issues/30). Using `-u NONE` works with packer.nvim but not vim-plug, and `--noplugin` works for both. 
I want to investigate performance implications from the change (so far, it seems like CPU time is *slightly* higher, but CPU usage is still minimal) and also verify check other plugin managers for compatibility.
> fix(client): fix rtp by using --noplugin

- lua/null-ls/builtins/formatting.lua
This adds the `-s` argument to stylua which causes stylua to automatically
search for a config file until the root is found and if no config is found it
uses config files in `$XDG_CONFIG_HOME` as a fallback. This is still a bit janky
as stylua doesn't seem to be informed of the root directory of the language
server and therefore seems to search for config files in the current `:pwd` of
vim itself.
> add stylua config search argument

- lua/null-ls/loop.lua
vim.loop.fs_mkstemp() is only exposed in luvit 1.34.1+ however nvim is built with 1.30.1. Provide a workaround until nvim updates luvit.
> Add workaround for systems without vim.loop.fs_mkstemp()

- lua/null-ls/builtins/code-actions.lua
Make sure gitsigns actions are run with the correct buffer context
> Run gitsigns actions with correct buffer

- lua/null-ls/builtins/diagnostics.lua
- lua/null-ls/client.lua
- lua/null-ls/code-actions.lua
- lua/null-ls/diagnostics.lua
- lua/null-ls/formatting.lua
- lua/null-ls/handlers.lua
- lua/null-ls/helpers.lua
- lua/null-ls/init.lua
- lua/null-ls/loop.lua
- lua/null-ls/lspconfig.lua
- lua/null-ls/state.lua
- lua/null-ls/utils.lua
Hi!
First of all, thank you for this amazing plugin.
This PR makes `null-ls` configurable with `lspconfig`.
With this change, autocommands or managing the null-ls client is now taken care of by lspconfig instead.
I haven't removed any code and haven't also change the way it works using `null-ls.setup`.
The lspconfig way is currently accessible by doing:
```lua
local nls = require("null-ls")
nls.setup_lspconfig({
sources = {
nls.builtins.formatting.prettierd,
nls.builtins.formatting.stylua,
nls.builtins.formatting.eslint_d,
nls.builtins.diagnostics.shellcheck,
nls.builtins.diagnostics.markdownlint,
nls.builtins.diagnostics.selene,
},
})
local lspconfig = require("lspconfig")
lspconfig["null-ls"].setup({ on_attach = function(client) end })
```
I also added a new builtin for …
> feat: added support for lspconfig & builtin for selene [DRAFT]

- lua/null-ls/init.lua
- lua/null-ls/rpc.lua
I found a fairly easy way to prevent the need to spawn a headless nvim to make rpc work.
This PR can be merged on your `lspconfig` branch.
What it does:
* wraps `vim.lsp.rpc.start` and will return a custom rpc implementation if the cmd is `nvim` (kept it like this for now so the normal way also still works, but ideally this should be changed to something like `null-ls`)
* everyhing that `server.lua` does is now handled by the curstom rpc.lua
* there's no longer any need for timers or server restarts
* implemented shutdown
Everything should work as before, but now without needing to spawn an actual nvim process 🙂
I left some debugging statements in there, that should be removed, but might be good if you want to test.
* the patching of the handlers could be removed and all moved inside the …
> feat: no longer needed to spawn nvim

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics.lua
[vale](https://docs.errata.ai/vale/about) is an open-source syntax-aware linter for prose built with speed and extensibility in mind (repo [here](https://github.com/errata-ai/vale)).
It supports adding syntax files (from, for instance, Linode, Gitlab or write-good) and per project syntax styles and it is quite fast.
* Added Diagnostics built-in `vale`.
* Parsed as JSON (all the buffer at once).
* The user is expected to have a `.vale.ini` or `_vale.ini` somewhere at `$HOME` or at the current working directory (you can take one from https://docs.errata.ai/vale/about#open-source-configurations, put the `.vale.init` at home and modify it to point to the `StylesPath`).
* Added some documentation.
TODO:
> feat: builtin vale

- lua/null-ls/builtins/diagnostics.lua
I forgot `vale`'s **suggestion** severity. This is a tiny PR that simply adds them.
`vale`'s **suggestion** severities are turned into LSP **hint (4)** severities (errors are 1 and warnings as 2, as before).
> enhance: show vale suggestions as style LSP diagnostics

- lua/null-ls/code-actions.lua
- lua/null-ls/diagnostics.lua
- lua/null-ls/formatting.lua
- lua/null-ls/generators.lua
- test/spec/generators_spec.lua
Exposes two functions:
- `require("null-ls.formatting").apply_edits`
- `require("null-ls.generators").run`
With this change, plugins built on top of `null-ls` will be able to use these as utility functions even if they don't want to use the LSP setup. For example:
- Provide command/keymaps to run formatters bypassing the LSP stuffs.
> Expose reusable function

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics.lua
- lua/null-ls/builtins/formatting.lua
Vue.js is typically handled with the same linter (diagnostics) and formatter as other JavaScript family files in the project.
> [Feature] Add vue filetype support to builtins

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting.lua
Fixes #50
Fixes #52 
also sorted the formatters, hope you don't mind :sweat_smile: 
- **c, cpp, cs, java**
- **asm**
- **beancount**
- **cmake**
- **crystal**
- **d**
- **dart**
- **elixir**
- **elm**
- **erlang**
- **fish**
- **go**
- **json**
- **nginx**
- **perl**
- **php**
- **python**
- **r**
- **ruby**
- **rust**
- **scala**
- **sql**
- **swift**
- **terraform**
- **vue**
> [Feature] Add extra formatters

- doc/MAIN.md
- lua/null-ls/builtins/diagnostics.lua
- lua/null-ls/config.lua
- lua/null-ls/diagnostics.lua
- lua/null-ls/generators.lua
- lua/null-ls/helpers.lua
- lua/null-ls/utils.lua
- test/spec/builtins/diagnostics_spec.lua
- test/spec/diagnostics_spec.lua
- test/spec/e2e_spec.lua
- test/spec/helpers_spec.lua
The main goal of this PR is to consolidate range conversion by clarifying that diagnostics provided to null-ls should be 1-indexed and sources are therefore responsible for offsetting their ranges if that's not the case.
As part of that, I've updated the new diagnostic helpers from #57 to allow sources to define optional offsets, which if present will be applied to each diagnostic before returning to the null-ls diagnostics handler. The handler is now only responsible for converting strings to numbers, setting defaults if necessary, and converting Lua ranges to the correct LSP format. 
So far, I've found that `write-good` uses 0-indexed columns. Other line-based built-ins probably need to be offset, too, but I think the best course of action is to rely on users to find and report issues. …
> Consolidate range conversion

- doc/BUILTINS.md
- lua/null-ls/config.lua
- lua/null-ls/helpers.lua
- lua/null-ls/utils.lua
- test/spec/config_spec.lua
- test/spec/helpers_spec.lua
Will close #60 when done.
This is a basic implementation that handles the conditional formatting case described in #60 as follows:
```lua
local sources = {
require("null-ls.helpers").conditional(function(utils)
return utils.root_has_file(".eslintrc.js") and b.formatting.eslint_d or b.formatting.prettier
end),
}
```
The above example shows a simple utility to check if a file exists in the current working directory. I mentioned in the linked issue that checking whether a command runs successfully is another option, and I'm open to adding more to handle common use cases. However, when it comes to handling more complicated cases (e.g. monorepos) or language-specific checks, I'd prefer to have users / integrations be responsible for writing the conditional logic. 
If registered …
> [WIP] feat: add conditional source registration

- lua/null-ls/builtins/diagnostics.lua
It seems like the way of handling the column position in null-ls changed, so this needs to be updated in the [vale](https://github.com/errata-ai/vale) diagnostics plug-in.
It only required to sum one to the end column position to be correct.
> Fix: set end column in vale properly

- .github/workflows/default.yml
- doc/BUILTINS.md
As discussed in #72 I cleaned up docs a bit.
- Added `selene` as it was [missing](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/74#issuecomment-891037232).
- Fixed some missing usage fields
- Fixed formatting in accordance to `markdown-lint`
May I also recommend integration of `markdown-lint` into the pipeline to run on PRs since people are often contributing to the docs as well and that would ensure consistency. I'd be happy to open a PR if you agree.   
closes #72
> add stylua on PRs, clean up BUILTINS.md

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting.lua
Adds the [deno formatter](https://deno.land/manual/tools/formatter) to `builtins`.
> feat: add deno fmt

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting.lua
It will format `*.fnl` file using [`fnlfmt`](https://git.sr.ht/~technomancy/fnlfmt)
> Add support formatting for `fennel` lang

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics.lua
- lua/null-ls/builtins/formatting.lua
- lua/null-ls/config.lua
Also formatted files under `lua/` according to contribution guidelines
`nixfmt` is a formatter for Nix code, intended to easily apply a uniform style
https://github.com/serokell/nixfmt
> Add nixfmt

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting.lua
NOTE: keymap setting
```vim
" It doesn't work.
<cmd>lua vim.lsp.buf.range_formatting()<CR>
" It works
:lua vim.lsp.buf.range_formatting()<CR>
```
> Add stylua range formatting.

- README.md
- doc/BUILTINS.md
- doc/CONFIG.md
- doc/MAIN.md
- lua/null-ls/builtins/test.lua
- lua/null-ls/code-actions.lua
- lua/null-ls/config.lua
- lua/null-ls/diagnostics.lua
- lua/null-ls/formatting.lua
- lua/null-ls/generators.lua
- lua/null-ls/helpers.lua
- lua/null-ls/methods.lua
- lua/null-ls/utils.lua
- test/files/test-file.txt
- test/spec/code-actions_spec.lua
- test/spec/config_spec.lua
- test/spec/diagnostics_spec.lua
- test/spec/e2e_spec.lua
- test/spec/formatting_spec.lua
- test/spec/generators_spec.lua
- test/spec/utils_spec.lua
Closes #56. Also includes a bunch of changes to generator methods that should not affect anyone and a few changes to debug logs to make them less useless. 
Previously, formatters ran simultaneously, which meant that registering more than one formatter was useless (or worse). This PR makes formatting sequential, meaning that users can register multiple formatters for a given filetype and have them run in the order in which they've been registered.
At the moment, I imagine that most null-ls users are defining built-in formatters in their own configurations, so this won't cause any surprises, but integrations that register formatters should be aware of this change, since spawning processes back-to-back will inevitably slow down formatting.
I work primarily with TypeScript and Lua, where …
> feat: make formatting sequential

- lua/null-ls/builtins/diagnostics.lua
- lua/null-ls/builtins/formatting.lua
Follow up on #105 
I just kept "--search-parent-directories"
Search parent directories for stylua.toml, if not found in current directory.
Ignored if config_path is provided. Keeps searching recursively up the parent
directory tree, until the root directory is reached. If not found, looks in
$XDG_CONFIG_HOME or $XDG_CONFIG_HOME/stylua
> Remove opinionated builtin parameters

- lua/null-ls/helpers.lua
Eg. https://github.com/polyzen/dotfiles/commit/a2c22dab0b68d6d4fdd9f57eb117ba0fffe873e1:
```lua
null_ls.builtins.diagnostics.shellcheck.with({
extra_args = function(params)
return params.ft == 'PKGBUILD' and { '--exclude', 'SC2148,SC2034,SC2154,SC2164' }
end,
filetypes = { 'PKGBUILD', 'sh' },
}),
```
> Allow extra_args to store a function

- lua/null-ls/builtins/formatting.lua
Since `--search-parent-directories` is added, maybe `--stdin-filepath` `$FILENAME` should be added to search the correct parent directories.
> chore(stylua): add --stdin-filepath $FILENAME

- lua/null-ls/builtins/diagnostics.lua
I have added the possibility of showing D messages in flake8. I have found this usefull when I combine flake8 with the [flake8-docstrings](https://pypi.org/project/flake8-docstrings/) pluggin.
> Added support for D messages in flake8

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting.lua
~~Blocked by https://github.com/surface-ui/surface_formatter/pull/37~~
This PR adds a new builtin formatter, [Surface Formatter](https://github.com/surface-ui/surface_formatter), that can format Surface template files.
> Feat: add Surface formatter

- doc/BUILTINS.md
Update 'codespell' docs to reflect actual default arguments.
> Update 'codespell' docs

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting.lua
Details:
- Make 'format_r' actually work by moving executable code to separate argument (this seems to be needed with `loop.spawn`). And also simplify code a bit.
- Remove opinionated `arrow = FALSE` parameter (as it seems preferable to be as less opinionated in builtins as possible).
- Use `range_formatting_args_factory` as this supports range formatting.
- Add 'styler' builtin. It has rather convoluted code to ensure there are no warnings (they are written to `stderr` and confuse this plugin).
If these changes are good enough, I'll update 'BUILTINS.md'.
> Update formatting for R language

- doc/HELPERS.md
- lua/null-ls/helpers.lua
- test/spec/helpers_spec.lua
Closes #151
This adds a new substitution argument `$ROOT` for the LSP workspace root path.
> Add `$ROOT` substitution arg for LSP workspace root

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting.lua
reference pull request that works in nvim formatter https://github.com/mhartington/formatter.nvim/pull/65
> Support rubocop formatting for ruby

- doc/HELPERS.md
- lua/null-ls/helpers.lua
- test/spec/e2e_spec.lua
- test/spec/helpers_spec.lua
Closes #167. The primary motivation is to allow LSP-style formatting for sources that don't support writing to `stdin`, but I can see it being useful elsewhere, too. 
This is still missing unit test coverage, and I'd like to add a simple E2E test using `prettier --write`.
> feat(helpers): add from_temp_file option

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics.lua
This commit adds [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) analyser.
Related to #170
> introduce phpcs diagnostic

- lua/null-ls/builtins/test.lua
- lua/null-ls/generators.lua
- lua/null-ls/helpers.lua
- test/spec/e2e_spec.lua
As discussed in #179 and the related issues, I suspected this was a regression, and in fact it was caused by cc612849a68c1eeb40986d6be50f11a5a9442acc. However, although multiple diagnostics were working well before this commit, there was still a risk of leaking, since the same `params` object was passed between generators. 
This PR moves the place where we copy params to the `generators` module, which makes more sense and simplifies testing, and also adds test coverage for this case to prevent future regressions. 
Thanks to everyone who reported issues and to @gbprod for putting in a fix.
> refactor: copy params per generator

- lua/null-ls/builtins/diagnostics.lua
Support for phpcs as a diagnostic tool was added to the builtins in https://github.com/jose-elias-alvarez/null-ls.nvim/pull/178, but (unless I'm doing something incorrectly) there were a few issues. 
Firstly, this adds some overrides to the JSON parsing of the phpcs output so that its properties are correctly mapped. In particular, the `severity` was probably not correct as phpcs's message `severity` property does not map directly to the ones used by `null-ls`.
Secondly, the output from phpcs is to STDOUT, not STDERR, and so this PR changes the builtin's `from_stderr` to `false` (this sometimes worked anyway because of a separate issue, see below).
Sometimes, additional status messages are included in the phpcs output even when reporting in JSON mode, creating invalid JSON. This PR also …
> Allow phpcs builtin messages to always reach output

- lua/null-ls/builtins/formatting.lua
Related to https://github.com/jose-elias-alvarez/null-ls.nvim/pull/185
Like `phpcs`, `phpcbf` returns a 1 or 2 exit code if it detects issues that need to be changed. The downside is that this exit code can be interpreted as meaning that the command failed, when in fact it did not (the result is that the stdout output ends up being moved to stderr by the formatter and not used).
This PR alters the phpcbf formatting builtin so that it will treat a 1 or 2 error code as a success, allowing formatting to proceed.
> Allow phpcbf builtin to consider exit codes 1 or 2 as success

- lua/null-ls/builtins/formatting.lua
Helps shfmt respect .editorconfig
Reference: https://github.com/mvdan/sh/blob/master/cmd/shfmt/shfmt.1.scd#parser-flags
> fix: pass filename to shfmt

- lua/null-ls/builtins/diagnostics.lua
- lua/null-ls/helpers.lua
- test/spec/helpers_spec.lua
This PR adds support for following external sources for [shellcheck](https://www.mankier.com/1/shellcheck).
I have added expanding `$DIRNAME` to the parent directory of the buffer. I could not find another way to make it work.
The newly added test passes. The only tests that do not pass also did not pass on `main`, so I don't think my changes are the root cause.
> Follow shellcheck external sources

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting.lua
Hi, I tracked down a problem when I tried to load with `formatting.trim_whitespace` and I noticed that `filetype` was missing, so I inserted one empty not sure if this is the right answer. At least this addressed the problem and since at [lines](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/config.lua#L89-L93) you validate they, I think it's necessary.
Regards,
Lucas
> Missing filetype in formatting.trim_whitespace

- lua/null-ls/builtins/formatting.lua
Fixes #208 
I also think this is a mistake, as the builtins docs clearly say that `edition=2018` is the default
> [rustfmt] change edition to `2018`

- doc/HELPERS.md
- doc/TESTING.md
- lua/null-ls/builtins/test.lua
- lua/null-ls/generators.lua
- lua/null-ls/helpers.lua
- test/spec/e2e_spec.lua
- test/spec/generators_spec.lua
Adds a `dynamic_condition` that is evaluated at "runtime" for all sources that discerns whether or not it will be run each time they have the potential to be run.
See associated discussion [here](https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/202) as to why this might be useful.
Some things still to do, but curious on your thoughts @jose-elias-alvarez before messing with getting these going:
> RFC - Dynamic source conditions

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting.lua
This PR follows a very similar structure to how `trim_whitespace` has been implemented to add a trailing newlines formatter.
* Adds new `trim_newlines` formatter
* Updates docs for usage information
> Add trim_newlines formatter

- doc/BUILTINS.md
- doc/HELPERS.md
- lua/null-ls/builtins/diagnostics.lua
- lua/null-ls/builtins/formatting.lua
- lua/null-ls/helpers.lua
- test/spec/helpers_spec.lua
Retrying #210.
Rubocop outputs both the violations it detected and the file contents to STDOUT. The command tried to pipe this to awk in order to cut off the first half and only output the formatted file contents.
This did not work as the command wasn't run in a shell and the pipes and shell constructs were passed as real command line arguments, which Rubocop confused to be other files to check. The `--stdin` option is not allowed together with filenames, and so Rubocop exited with an error.
Adding the `--stderr` option to Rubocop makes it output only the file contents to STDOUT and the violations to STDERR.
Added a new option called `ignore_stderr` that resets STDERR after running the command so the command doesn't fail because of operator output.
Now the formatter works correctly. …
> Fix rubocop formatter, add diagnostics, add standardrb for both

- doc/BUILTINS.md
I noticed this while perusing the docs.
> Repair dead rubocop link

- lua/null-ls/builtins/diagnostics.lua
- test/spec/builtins/diagnostics_spec.lua
Add rules info like `MD012/no-multiple-blanks` as `diagnostics.code`. All rules are in [here](https://github.com/DavidAnson/markdownlint/#rules--aliases)
This is what it look in [trouble.nvim](https://github.com/folke/trouble.nvim).
Without `diagnostics.code`
With `diagnostics.code`
> feat(markdownlint): add rule info

- lua/null-ls/builtins/formatting.lua
when rust logging is active globally ( via setting `RUST_LOG=trace` )
`rustfmt` will print debug output to stderr.
I manually tested this with a new, custom source so I assume this will also work. 
I'm happy to add any needed documentation or tests if I need to.
> fix: ignore stderr output when running rustfmt

- lua/null-ls/builtins/formatting.lua
Black accepts --stdin-filename since its 21.5b0 release: https://github.com/psf/black/releases/tag/21.5b0
> Pass `--stdin-filename` for black

- lua/null-ls/builtins/formatting.lua
Omit `--fix` flag, which modifies file directly, but doesn't buffer.
> fix(builtins): let `fnlfmt` know which buffer to run on

- lua/null-ls/builtins/code-actions.lua
- lua/null-ls/builtins/diagnostics.lua
Statix changed default diagnostics output in https://github.com/nerdypepper/statix/commit/1a97cce01f8e49b33bf28cbcdfeb3c8aefd809a5
> statix: output change from stdout to stderr

- README.md
- doc/BUILTINS.md
- doc/MAIN.md
- lua/null-ls/builtins/completion.lua
- lua/null-ls/builtins/init.lua
- lua/null-ls/completion.lua
- lua/null-ls/generators.lua
- lua/null-ls/methods.lua
- lua/null-ls/rpc.lua
- lua/null-ls/utils.lua
- test/spec/completion_spec.lua
Just creating a PR to get some early feedback. I thought I could base the completion feature on the way hover works.
I'm not yet so sure about extending the `generator_opts` to support external processes for completion yet. I want to understand your point of view on this feature before investing too much time in the wrong direction.
I started testing it with my own config [here](https://github.com/Furkanzmc/dotfiles/blob/master/vim/lua/vimrc/null_ls_sources.lua#L158).
I want to express my appreciation for this plug-in again. It's awesome work! I'm looking forward to pushing it to the limits.
Let me know what you think of my changes and the direction you want to take.
-----
I didn't add any tests yet. I'll do that once I get your feedback.
-----
**Q_1**: Is there a way to report the …
> feat: Initial implementation for completion support

- lua/null-ls/builtins/diagnostics/credo.lua
- test/spec/builtins/diagnostics_spec.lua
When working on a project that logs out a warning if loading a
dev.secret.exs file, I noticed that vscode users did not have any
issues. Taking a look through the plugin, it looks for the first
occurance of a `{` and parses from there.
https://github.com/pantajoe/vscode-elixir-credo/blob/main/src/execution.ts#L44
> Handle compile warnings preceeding credo output

- lua/null-ls/builtins/diagnostics/mypy.lua
Closes #139.
Here is my attempt to add the mypy built-in. It differs from #155 in these ways:
- instead of using a temporary file, it uses a `--command` parameter with a file content,
- it includes exit code 2 as a positive result,
- it also parses diagnostic codes.
As for the exit code, I will ask upstream if they could add a separate exit code for syntax errors.
**EDIT:** I've just noticed that the spawn `mypy` processes don't close, so they fill up the whole CPU
> feat(builtins): add mypy built-in

- doc/BUILTINS.md
1. Removed `zsh` filetype. AFAIK this was recently removed from the formatter.
2. `shfmt` args were not empty inside the code. So I updated the docs accordingly.
> docs(builtins): update `shfmt` config

- doc/BUILTINS.md
- doc/CONFIG.md
- doc/MAIN.md
- doc/SOURCES.md
- lua/null-ls/code-actions.lua
- lua/null-ls/config.lua
- lua/null-ls/diagnostics.lua
- lua/null-ls/formatting.lua
- lua/null-ls/generators.lua
- lua/null-ls/handlers.lua
- lua/null-ls/helpers.lua
- lua/null-ls/info.lua
- lua/null-ls/init.lua
- lua/null-ls/lspconfig.lua
- lua/null-ls/rpc.lua
- lua/null-ls/sources.lua
- lua/null-ls/utils.lua
- test/spec/code-actions_spec.lua
- test/spec/config_spec.lua
- test/spec/e2e_spec.lua
- test/spec/generators_spec.lua
- test/spec/helpers_spec.lua
- test/spec/info_spec.lua
- test/spec/lspconfig_spec.lua
- test/spec/rpc_spec.lua
- test/spec/sources_spec.lua
- test/spec/utils_spec.lua
The goal of this PR is to simplify how sources are registered to clean up a messy portion of the code base and enable new features, namely:
- Disabling filetypes per source (i.e. enable all filetypes besides a subset)
- More transparent querying of registered sources (no need to go through the info API, which isn't really ideal for consumption)
- Disabling sources
- Registering an arbitrary number of sources with the same name (which lets through duplicates, but that hasn't been an issue AFAIK)
- ~~Running sources on demand (not really related, but something I want to include)~~ out of scope and not really consistent with the goal of LSP-like behavior
Currently, generators are stored independently and anonymously, making it impossible to disable them or otherwise manipulate them once …
> feat: improve source API

- README.md
- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/golangci_lint.lua
- lua/null-ls/config.lua
- lua/null-ls/diagnostics.lua
- lua/null-ls/formatting.lua
- lua/null-ls/generators.lua
- lua/null-ls/handlers.lua
- lua/null-ls/lspconfig.lua
- lua/null-ls/methods.lua
- lua/null-ls/rpc.lua
- lua/null-ls/sources.lua
- test/spec/diagnostics_spec.lua
- test/spec/e2e_spec.lua
- test/spec/formatting_spec.lua
- test/spec/generators_spec.lua
- test/spec/sources_spec.lua
Closes #166 and supersedes #318.
The main change in this PR is to migrate to the `vim.diagnostic` API when available, the biggest advantage of which is the ability to use separate namespaces for each source. This lets us push multiple sets of diagnostics at a time, which enables running linters on save (more on this in a bit) and lays the groundwork for better source management, as mentioned in #337. It's also simpler to use, both internally and from a user config perspective.
Previously, pushing diagnostics on `textDocument/didSave` notifications wasn't possible for the reasons discussed in #166, but with the diagnostic API in place, adding support was simple. The one issue was handling `textDocument/didOpen` notifications, since these should prompt null-ls to run both on-change and …
> feat: migrate to diagnostic API and support linting on save (feat. golangci-lint)

- doc/CONFIG.md
- lua/null-ls/lspconfig.lua
Allows to explicitly set the project root for certain projects
> add .null-ls-root to LSP root patterns

- README.md
- doc/CONFIG.md
- lua/null-ls/code-actions.lua
- lua/null-ls/completion.lua
- lua/null-ls/config.lua
- lua/null-ls/diagnostics.lua
- lua/null-ls/formatting.lua
- lua/null-ls/generators.lua
- lua/null-ls/helpers.lua
- lua/null-ls/hover.lua
- lua/null-ls/info.lua
- lua/null-ls/init.lua
- lua/null-ls/logger.lua
- lua/null-ls/loop.lua
- lua/null-ls/rpc.lua
- lua/null-ls/utils.lua
- test/spec/e2e_spec.lua
- test/spec/formatting_spec.lua
- test/spec/generators_spec.lua
- test/spec/utils_spec.lua
- Set the correct stack level in plenary.log
- Use all the levels of logging with the ability of using the console
- Switch `echo_error` to use `Log:warn()`
- Switch most of `u.debug_log()` to `Log:trace()` while keeping some of them as `Log:debug()`
Fixes #280
- fix(logger): configurable logging behavior
- fix(logger): restore the quick debug toggle
- fix(logger): rebase
- chore: use lower-case for logger instances
- fix(logger): explicit mention of empty completion
- chore: naming convention
> fix(logger): configurable logging behavior

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/google_java_format.lua
This PR adds a builtin formatting source for [google-java-format](https://github.com/google/google-java-format).
I believe I've followed the format for documentation properly, the only thing that might be a little out of the ordinary is that I added another section inside usage showing how to use it with the `--aosp` option since I think many people will want to do that. If there's a different heading that should go under, lmk!
> feat(formatting): add google-java-format

- lua/null-ls/builtins/diagnostics/golangci_lint.lua
I had mentioned all of this in code-review comments in #318, for details please have a look there.
Here are the changes I suggested.
It's necessary to ignore stderr from golangci-lint for now as otherwise the deprecation warnings of various linters used by golangci-lint will cause issues.
Also as most of the linters show non-critical issues in the code, settings the default severity to warning makes sense. Otherwise all the warnings will show up as errors.
> fix golangci-lint issues

- doc/BUILTINS.md
- doc/HELPERS.md
- lua/null-ls/diagnostics.lua
- lua/null-ls/helpers.lua
- lua/null-ls/state.lua
- lua/null-ls/utils.lua
- test/files/cat
- test/spec/diagnostics_spec.lua
- test/spec/e2e_spec.lua
- test/spec/helpers_spec.lua
- test/spec/state_spec.lua
- test/spec/utils_spec.lua
Closes #289.
This PR adds two new options for built-ins, `prefer_local` and `only_local`. It also exposes the underlying `dynamic_command` mechanism for generators created using `generator_factory`. 
When a source with `prefer_local = true` runs for the first time in a given buffer, null-ls will traverse that buffer's parent directories and try to find a local copy of `command`, stopping once it hits the client's root directory. If not found, it will fall back to a globally-available executable. The results of the search are cached and used whenever the source runs again. `only_local` works the same way without falling back (i.e. it only runs if a local copy is found).
Both options accept a string, which is treated as a prefix (see the documentation for an example).
If found, the `cwd` of …
> feat(builtins): add prefer_local and only_local options

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/hadolint.lua
This was removed from lsp-config, so my initial reason for adding it is
now invalid. See:
https://github.com/neovim/nvim-lspconfig/pull/1358
Reverts 7852d82f3904a6a70620d328e6e44f9bbc8e4a27
Original PR:
https://github.com/jose-elias-alvarez/null-ls.nvim/pull/271
> feat(hadolint): remove Dockerfile from filetypes

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/staticcheck.lua
This PR will add staticcheck. Compared to the implementation I used for [nvim-lint](https://github.com/mfussenegger/nvim-lint/blob/master/lua/lint/linters/staticcheck.lua), the whole project will be linted instead of a single file. This prevents false positives like `undeclared name`.
> feat(diagnostics): add staticcheck

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/revive.lua
Like most golang linters revive can lint a whole project at once as well. So if you implement https://github.com/jose-elias-alvarez/null-ls.nvim/pull/351, I would probably adjust this.
> feat(diagnostics): add revive

- lua/null-ls/builtins/formatting/isort.lua
Currently `isort` is formatting stub files (`.pyi` extension) incorrectly because it doesn't know whether the input is a stub file or a regular Python file. This PR fixes that problem by specifying the filename when calling `isort`.
> Specify filename when calling isort

- lua/null-ls/builtins/formatting/phpcbf.lua
Ref: https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/341
> Use `--stdin-path` argument in phpcbf to make exclude-pattern works

- doc/BUILTINS.md
- lua/null-ls/builtins/code_actions/gitrebase.lua
Wrote this for me but I think it could be interesting as a builtin.
This introduce a code action to change the command of a line in an interactive git rebase.
Eg. this will switch from `pick abcede feat(gitrebase): introduce gitrebase builtin` to `fixup abcede feat(gitrebase): introduce gitrebase builtin`
Feel free to merge or decline ;)
> feat(gitrebase): introduce gitrebase builtin

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/yapf.lua
Enable range formatting for yapf & black
> feature(yapf): allow range_format

- doc/BUILTINS.md
- lua/null-ls/builtins/code_actions/shellcheck.lua
Adds shellcheck code actions to disable the rule under the cursor, either at the line level or the file level. If a `disable=` directive already exists, the rule’s code is appended to it.
Note: Shellcheck allows arbitrary blank lines between line directives and the target line or the shebang/BOF and the file-level directive. This case is currently not handled intelligently; a new directive is added rather than updating the existing one.
I didn't add tests because I don't see any tests for other code actions builtins.
> feat(builtins): add shellcheck code actions

- lua/null-ls/builtins/diagnostics/teal.lua
Previously, the command is `tl` while the filename is `teal.lua`.
So it results in duplicate registration.
This PR fixes it by setting its name to `teal`
> fix(teal): avoid duplicate registration

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/ansiblelint.lua
Tihs PR adds [ansible-lint](https://github.com/ansible-community/ansible-lint) as a diagnostic source.
It should respect `.ansible-lint` as well.
> feat(diagnostics): add ansible-lint

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/gccdiag.lua
Get diagnostics from gcc with the correct compiler arguments
Requires a `compiler_commands.json` file at the root of the working directory.
> Add a builtin for using `gccdiag`

- README.md
- doc/BUILTINS.md
- doc/SOURCES.md
- lua/null-ls/config.lua
- lua/null-ls/diagnostics.lua
- lua/null-ls/handlers.lua
- lua/null-ls/init.lua
- lua/null-ls/lspconfig.lua
- lua/null-ls/rpc.lua
- lua/null-ls/sources.lua
- lua/null-ls/utils.lua
- test/spec/diagnostics_spec.lua
- test/spec/init_spec.lua
- test/spec/lspconfig_spec.lua
- test/spec/sources_spec.lua
- test/spec/utils_spec.lua
This PR removes support for Neovim 0.5.1, which simplifies the code base and enables new 0.6-exclusive features (e.g. #376). The goal is to merge this in a couple of weeks once the new version is more widespread and keep a branch pinned at the last commit before merging (with the caveat that I will no longer write or merge fixes for 0.5.1).
> refactor!: remove 0.5.1 support

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/djhtml.lua
Add [djhtml](https://github.com/rtts/djhtml) as formatting source.
I tried to run the tests but they broke in my face with some error that didn't found a module `plenary.test_harness`, checking out other PRs that add new sources I see they don't add any test so I guess this part of the code doesn't require tests at the time being, if they do let me know.
> Add djhtml formatter

- lua/null-ls/builtins/formatting/shellharden.lua
When I enable the shellharden builtin, I encounter a bug whereby any modifications I make to a file are reverted when saving the file.
I found that I could work around this by modifying the parameters given to shellharden when configuring null-ls; this change makes those the default.
> Make shellharden overwrite rather than output to stdout

- lua/null-ls/builtins/diagnostics/cspell.lua
1. Activate cspell on all files (as indicated in BUILTINS.md)
2. Only underline the incorrect word, and not the entire line from the
word on
> feat: Improve cspell

- doc/BUILTINS.md
Just fixing the link to the Flake8 Github page.
> Fix: url for Flake8 in BUILTINS.md

- Makefile
- README.md
- doc/HELPERS.md
- lua/null-ls/loop.lua
- test/spec/loop_spec.lua
Obviously this is not super useful for things like diagnostics, but for something that doesn't run as often (like formatters) it is useful to be able to do something like:
```lua
local function check_exit_code(code, stderr)
local success = code == 0
if not success then
vim.notify({ "Formatting failed", stderr })
end
return success
end
```
to know _why_ the operation failed. There are other things that could be passed here (e.g. `stdout`) but I only really see a use case for `stderr`.
> Pass STDERR to check_exit_code

- lua/null-ls/health.lua
This is a basic implementation of the `:checkhealth` functionality.
Closes #392.
I used the following `Dockerfile` and `init.lua` to test the functionality. Inside the Docker container I just opened `nvim` and executed `:checkhealth null-ls`.
<details>
<summary><code>Dockerfile</code></summary>
```Dockerfile
FROM debian:buster-slim
FROM rust:latest
RUN apt-get update && apt-get install -y curl git nodejs npm python3 python3-pip
RUN cargo install stylua
RUN pip3 install black
RUN npm i -g prettier @fsouza/prettierd markdownlint-cli
WORKDIR /tmp
RUN curl -LO https://github.com/neovim/neovim/releases/download/v0.6.0/nvim-linux64.tar.gz
RUN tar xzf nvim-linux64.tar.gz -C /opt
ENV PATH /opt/nvim-linux64/bin:$PATH
WORKDIR /root/.local/share/nvim/site/pack/packer/start
RUN git clone …
```
> feat: add :checkhealth support (WIP)

- lua/null-ls/builtins/_meta/completion.lua
- lua/null-ls/builtins/_meta/diagnostics.lua
- lua/null-ls/builtins/_meta/filetype_map.lua
- lua/null-ls/builtins/_meta/formatting.lua
- lua/null-ls/builtins/diagnostics/credo.lua
- test/spec/builtins/diagnostics_spec.lua
Instead of attempting to decode json and falling back to a substring,
try to find json in the raw output first. This should also hopefully
solve some occasional errors when the output having some values that the
decode doesn't like.
Also tried to get rid of the nested conditionals with some early
returns.
Closes #443
> fix(diagnostics): Use raw substring for credo

- scripts/autogen_metadata.lua
Sort the generated metadata tables to ensure consistent results on repeated runs.
> ci: sort the metadata table for consistency

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/nimpretty.lua
Hello,
this pull requests adds the `nimpretty` formatter for `Nim` code.
I successfully tested it on some Nim projects.
If there are some suggestions or changes I will gladly apply them and report back.
> add nimpretty Nim code formatter to builtins

- lua/null-ls/builtins/diagnostics/mypy.lua
<string> doesn't work to catch filepath before the first `:`, uses
`[^:]+` instead.
> fix(builtins): mypy output pattern

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/joker.lua
[joker](https://github.com/candid82/joker)
> `joker --format -` - read Clojure source code from standard input, format it and print the result to standard output.
There's no open issues to resolve.
> feat: Add `joker` formatter for Clojure

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/ptop.lua
Hello,
this pull requests adds the `ptop` formatter for `Pascal` code.
I successfully tested it on some `Pascal` projects.
If there are some suggestions or changes I will gladly apply them and report back.
> add ptop Pascal code formatter to builtins

- lua/null-ls/builtins/diagnostics/mypy.lua
Using --command $TEXT even if the text looks correctly escaped mypy
sometimes we pass multiple arguments to --command and fail with:
output: usage: mypy [-h] [-v] [-V] [more options; see below]
[-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: May only specify one of: module/package, files, or command.
This change uses directly --shadow-file $ORIGINAL_FILENAME $FILENAME
$REAL_FILENAME instead of --command $TEXT to avoid this.
> fix(builtins): mypy replace --command by --shadow-file

- lua/null-ls/utils.lua
If a folder has a wildcard in it's path, the plugin gives a `Reverse range in character class` error. I had the same problem in the past with another plugin: https://github.com/airblade/vim-rooter/issues/122. The solution is simple: escape any wildcard characters.
Here is a small snippet to reproduce my error: `folder_name="[u-a]" && mkdir -p "$folder_name" && touch "$folder_name/readme.md" && nvim "$folder_name/readme.md"`.
> fix(utils): escape wildcard characters in folder path

- lua/null-ls/sources.lua
- test/spec/sources_spec.lua
Neovim supports setting multiple filetypes through the use of a dot
separator. From `:h 'filetype'`:
When a dot appears in the value then this separates two filetype
names.  Example:
/* vim: set filetype=c.doxygen : */ ~
This will use the "c" filetype first, then the "doxygen" filetype.
This works both for filetype plugins and for syntax files.  More than
one dot may appear.
By respecting this functionality, users can set filetypes such as
`json.openapi` or `yaml.docker-compose` and get out-of-the-box support
for multiple filetype-specific sources in a single file.
Dotted filetypes continue to be supported as a unique filetype for
backward compatibility and cases where sources should only be made
available at the intersection of filetypes.
For files where a source is explicitly configured …
> fix: Add support for dotted filetypes

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/rustfmt.lua
The Rust 2021 edition has been released. So I think it would be better to use 2021 edition for rustfmt.
related: https://github.com/rust-lang/rustfmt/pull/4847
> fix(rustfmt): remove edition in default arguments

- lua/null-ls/builtins/diagnostics/credo.lua
- test/spec/builtins/diagnostics_spec.lua
I thought I was going crazy when I simply couldn't get Credo to show error results after I got ESLint working pretty effortlessly. But I think I accidentally stumbled on some code that was broken by a recent refactor.
> fix(credo): use callback instead of returning value

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/cue_fmt.lua
Uses the `fmt` command of the `cue` CLI tool to format [CUE lang](https://cuelang.org/) files.
> feat(builtin): Add `cue fmt` based formatter

- lua/null-ls/builtins/diagnostics/standardjs.lua
- test/spec/builtins/diagnostics_spec.lua
My initial integration of standardjs to null-ls treated all diagnostics emitted as errors.
However, standardjs does distinguish between syntax errors (denoted by "Parsing error") and warnings (usually code-style).
An example of a syntax error:
/home/fred/foo.js:2:1: Parsing error: Unexpected token
And an example of a code-style warning:
/home/fred/foo.js:1:35: Strings must use singlequote.
The null-ls integration of standardjs now accounts for errors as against warnings.
> feat: standardjs fine grained severities

- doc/CONFIG.md
- lua/null-ls/client.lua
- lua/null-ls/config.lua
Adds on_exit callback.
I'm setting some stuff up in on_init and on_attach that needs to be cleaned up in on_exit.
> feat: forward on_exit callback from lsp client

- doc/BUILTINS.md
Previous link target was not handled as a web adress, but instead linked to [https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/mypy-lang.org](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/mypy-lang.org), which does not exist. I added in the link to the [official mypy github repo](https://github.com/python/mypy).
> Fix broken mypy link

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/cue_fmt.lua
- test/spec/builtins/diagnostics_spec.lua
Takes advantage of the fact that `cue fmt` returns errors to `stdout` when invalid syntax is encountered and provides them as diagnostics. [CUE](https://cuelang.org/)
I tried using helpers (e.g. `from_pattern`) to reduce lines of code however I couldn't come up with pattern to match the output from `cue fmt`. Each issue spans two lines, first the error message then the position.
```sh
expected label or ':', found 'INT' 42:
./foo.cue:3:2
missing ',' in struct literal:
./foo.cue:5:7
```
> feat(builtin): Add `cue fmt` diagnostic

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/gitlint.lua
Adds `gitlint` diagnostic source, for checking git commit messages: https://jorisroovers.com/gitlint/
Unfortunately [`gitlint` doesn't support receiving data over stdin from sockets](https://github.com/jorisroovers/gitlint/blob/3c017995633f602125f7caaa91e96bb767ca5953/gitlint-core/gitlint/cli.py#L121-L122), so I had to use the temporary-file strategy to make it work.
> feat(builtin): Add `gitlint` diagnostic

- doc/BUILTINS.md
Update Luacheck link to the official repo: https://github.com/lunarmodules/luacheck
> Update Luacheck link

- lua/null-ls/builtins/diagnostics/flake8.lua
Closes https://github.com/jose-elias-alvarez/null-ls.nvim/issues/487
In this code I added following:
1. Only first character after start_col is highlighted, unless:
2. Some specific errors, where one can highlight variable names, because they are specified as error source in flake8 message
> feat: flake8 end_col highlight adapter

- lua/null-ls/utils.lua
`params` doesn't contain a `bufnr` field.
Fixes this error:
```
Error executing vim.schedule lua callback: ...//pack/packages/start/null-ls.nvim/lua/null-ls/utils.lua:14: Expected Lua number
stack traceback:
[C]: in function 'nvim_buf_get_option'
...//pack/packages/start/null-ls.nvim/lua/null-ls/utils.lua:14: in function 'get_line_ending'
...//pack/packages/start/null-ls.nvim/lua/null-ls/utils.lua:56: in function 'resolve_content'
...//pack/packages/start/null-ls.nvim/lua/null-ls/utils.lua:110: in function 'make_params'
.../packages/start/null-ls.nvim/lua/null-ls/diagnostics.lua:145: in function 'handler'
...im//pack/packages/start/null-ls.nvim/lua/null-ls/rpc.lua:103: in function 'notify'
...f/Projects/tools/nvim/share/nvim/runtime/lua/vim/lsp.lua:484: in function …
```
> fix: Use bufnr from the function parameter

- doc/BUILTINS.md
- doc/HELPERS.md
- lua/null-ls/helpers/generator_factory.lua
- lua/null-ls/helpers/make_builtin.lua
- lua/null-ls/loop.lua
- test/spec/helpers/generator_factory_spec.lua
- test/spec/loop_spec.lua
closes #385
- Adds another option field to pass in environment variables as in dictionary form.
Currently merges operating system variables first to match the default behavior used in the `neovim` repository.
What I could not manage to do because of `null-ls` first checking the command to be executable is extending the environment variables while doing that to match the behavior in the `lsp-installer` breaking change commit [here](https://github.com/williamboman/nvim-lsp-installer/commit/095ab4eb6a02d5fd3ea4b782a0e868e2c65e4427) where it now uses extending the `PATH` variable without using the absolute path of the executable. If you have any advice on that, I guess I can further improve this by injecting environment variables to the initial check of the file being executable, so that this …
> feat: environment variable injection

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/textlint.lua
Hi, thanks for the great software!
I tried to add textlint to null-ls, as I often use textlint when writing.
I'm afraid I wrote the same function in several places, but I couldn't think of a better way. Since the diagnostics are compatible with eslint, I wrote the same function as eslint.
Please review.
> feat(builtin): Add `textlint` diagnostic

- lua/null-ls/builtins/diagnostics/rubocop.lua
The `start_column` and `last_column` properties are under the `location` property in RuboCop's JSON output, not at the top-level. Previously the builtin for RuboCop was extracting these from the wrong location, so diagnostics were not annotated with the correct begin and end points.
This fixes the builtin so that it sources `start_column` and `last_column` from the correct place.
I have tested this locally by creating a custom source for RuboCop with this change, and the diagnostics have the correct start and end columns.
**Before**
**After**
> fix(rubocop): extract column info from location

- lua/null-ls/helpers/generator_factory.lua
- lua/null-ls/loop.lua
- test/spec/helpers/generator_factory_spec.lua
- test/spec/loop_spec.lua
May close #483. 
I can't reliably replicate the error, but based on the message and trace, I'm pretty confident the issue is that we are calling the same async callback multiple times. This PR prevents that situation, which (if I'm right) should fix the issue.
@horseinthesky @ahhshm Could you please try this fix and see if it makes a difference?
> fix(loop): guard against multiple on_close calls

- doc/BUILTINS.md
- lua/null-ls/builtins/code_actions/eslint.lua
- lua/null-ls/builtins/diagnostics/eslint.lua
- lua/null-ls/builtins/diagnostics/standardjs.lua
- lua/null-ls/builtins/formatting/eslint.lua
- lua/null-ls/builtins/formatting/prettier.lua
- lua/null-ls/builtins/formatting/prettier_d_slim.lua
- lua/null-ls/builtins/formatting/prettier_standard.lua
- lua/null-ls/builtins/formatting/prettierd.lua
- lua/null-ls/builtins/formatting/rustywind.lua
- lua/null-ls/builtins/formatting/stylelint.lua
- lua/null-ls/helpers/command_resolver.lua
- lua/null-ls/helpers/generator_factory.lua
- lua/null-ls/helpers/make_builtin.lua
- lua/null-ls/utils.lua
Make use of `dynamic_command` as a fallback when the base command isn't found. This is particularly useful for node_modules, for example: `prettier`.
```lua
generator_opts = {
command = "prettier",
args = h.range_formatting_args_factory({ "--stdin-filepath", "$FILENAME" }),
to_stdin = true,
dynamic_command = require("null-ls.helpers.command_resolver").from_node_modules
}
```
Related discussion: https://github.com/jose-elias-alvarez/null-ls.nvim/pull/349#pullrequestreview-807707808
> feat: add fallback dynamic cmd by default

- lua/null-ls/logger.lua
hi! it seems the `config.log.enable` option isn't working for me, and I can't find any other references to it
> fix(logger): respect config.log.enable

- lua/null-ls/builtins/_meta/filetype_map.lua
- lua/null-ls/builtins/_meta/formatting.lua
- lua/null-ls/builtins/formatting/cabal_fmt/cabal_fmt.lua
Resolved: #563 
* "cabal-fmt" is original command name, I changed it to underscore for lib.
> feat: cabal-fmt formatting source for cabal files

- lua/null-ls/builtins/diagnostics/qmllint.lua
The latest qmllint now uses a configuration file so the users can just use that file to configure the settings. For earlier versions, I think using `with({})` to change how qmllint is run still an option.
> Fix: Update qmllint parameters and args

- doc/BUILTINS.md
- lua/null-ls/builtins/_meta/diagnostics.lua
- lua/null-ls/builtins/_meta/filetype_map.lua
- lua/null-ls/builtins/diagnostics/protolint.lua
- test/spec/builtins/diagnostics_spec.lua
Adds [protolint](https://github.com/yoheimuta/protolint) diagnostic for `.proto` files.
Since [protolint](https://github.com/yoheimuta/protolint) doesn't support input from `stdin` a temporary file is used instead.
This was initially implemented with `from_json`  but had to be reworked since [protolint](https://github.com/yoheimuta/protolint)  spits out `plaintext` instead of `json` when its parsing invalid `.proto` files.
The final implementation is based on the  [credo](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/credo.lua) diagnostic.
Let me know if anything needs to be adjusted.
> feat(builtin): Add protolint diagnostic

- lua/null-ls/formatting.lua
- lua/null-ls/utils.lua
May fix #569.
The changes to `u.buf.content()` should be safe, since unless explicitly specified both `eol` and `fixeol` will be `true`, but the change to `edit.newText` is a bit more complicated. The issue is that most (all?) formatters that support `stdout` also output a final newline that isn't part of the "actual" content. This hasn't been a problem so far because [`vim.lsp.util.apply_text_edits()` will remove it](https://github.com/neovim/neovim/blob/b65a23a13a29176aa669afc5d1c906d1d51e0a39/runtime/lua/vim/lsp/util.lua#L476) unless `fixeol` is `false`.  
These changes seem to handle the case in the linked issue without affecting the default case. I'm not thrilled with this, as it relies on the internal behavior of `apply_text_edits()`, and I think that creating our own version of the …
> fix(formatting): properly handle nofixeol

- README.md
Having this problem my self, and seeing this message pop up in the issues (#572) of this project, I decided to create this little FAQ in the FAQs section.
Problem here: In my case, `rubocop` took longer than the default timeout, so I decided to drop the formatting for rubocop, since it takes to long. Other solution would be to just increase the timeout for any `formatting_sync` call, however this slowed down my editor performance massively, so I just dropped formatting support.
> Add faq for timeout error message to FAQ section in README.md

- lua/null-ls/builtins/formatting/goimports.lua
sometimes goimports has a hard time automatically importing packages that are in your current project, and imports some random 3rd party one with the same name. makes sense since all it's reading from is stdin
from `goimports -h`
```
usage: goimports [flags] [path ...]
...
-srcdir dir
choose imports as if source code is from dir. When operating on a single file, dir may instead be the complete file name.
...
```
I have been using this for a while and it is also making saves go from like 1s+ to milliseconds 
also @abzcoding  it seems you added the original goimports builtin, can you see any drawbacks here? thanks!
> feat(builtins): set -srcdir in goimports

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/protoc_gen_lint.lua
- test/spec/builtins/diagnostics_spec.lua
Adds [protoc-gen-lint](https://github.com/ckaznocha/protoc-gen-lint) diagnostic for `.proto` files.
Since [protoc-gen-lint](https://github.com/ckaznocha/protoc-gen-lint) doesn't support input from `stdin` a temporary file is used instead.
This was initially implemented with `from_pattern` but had to be reworked with an additional matching pattern since [protoc-gen-lint](https://github.com/ckaznocha/protoc-gen-lint) spits out errors in a different format when its parsing invalid `.proto` files.
Let me know if anything needs to be adjusted.
> feat(builtint): Add protoc-gen-lint diagnostic

- lua/null-ls/builtins/diagnostics/mypy.lua
Similar to what was happening on #575. `mypy` returns errors found in files referenced by the current one. This adds the filename to the diagnostics result so that they are properly handled.
> fix: Fix multifile parsing for mypy

- lua/null-ls/builtins/diagnostics/ansiblelint.lua
- test/spec/builtins/diagnostics_spec.lua
There was an issue with parsing severities containing `_`.
This also adds parsing of the error code as well as a test.
Unfortunately, I can't seem to figure out why the test fails.
It works correctly when I run it on an actual file and the match pattern seems to work when executed on the test output.
```sh
echo 'print(string.match([[path/to/file.yaml:2: [risky-file-permissions] [VERY_HIGH] File permissions unset or incorrect]], [[^[^:]+:(%d+): %[([%w-]+)%] %[([%w_]+)%] (.*)$]]))' | lua
2	risky-file-permissions	VERY_HIGH	File permissions unset or incorrect
```
But when I run the test I get
```
Fail	||	diagnostics ansiblelint should create a diagnostic
./test/spec/builtins/diagnostics_spec.lua:804: Expected objects to be the same.
Passed in:
(nil)
Expected:
(table: 0x0102e82a10) {
[code] = …
```
> fix(diagnostics): Fix ansible-lint parsing

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/cljstyle.lua
Adds `cljstyle` formatter for `clojure` code.
Let me know if something does not look right.
> feat(builtins): Add cljstyle formatter for clojure code

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/raco_fmt.lua
Added [raco fmt](https://docs.racket-lang.org/fmt/) tool for formatting Racket files and updated `BUILTINS.md` doc file.
> feat: Added raco fmt builtin for formatting Racket files

- lua/null-ls/builtins/formatting/fnlfmt.lua
- lua/null-ls/builtins/formatting/raco_fmt.lua
Because `fnlfmt` and `raco fmt` were formatting with `$FILENAME` in their args, it led to unsaved changes not being reflected in formatting on save. Using stdin seems to solve this.
> fix: corrected format on save behaviour for fnlfmt and raco fmt

- lua/null-ls/client.lua
May fix j-hui/fidget.nvim#9. 
Calling a progress handler inside of an async callback can cause issues if that handler does something that's blocked by textlock. This change schedules the call to prevent the issue.
If a user of fidget.nvim can confirm that this fixes the issue, I'll merge it.
> fix(client): schedule progress handler call

- doc/CONFIG.md
- lua/null-ls/client.lua
- lua/null-ls/config.lua
- test/spec/client_spec.lua
Per the discussion in #502, there are some buffers we always want null-ls to ignore, regardless of filetype or buftype.
Allow the user to hook into the existing `should_attach` function in the client by specifying a callback on the config object.
> feat(config): add optional user-defined should_attach callback

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/styler.lua
Currently the `styler` formatter does not format `rmd` files. The `styler::style_text()` function does not support the content of Rmarkdown files.
This PR add support for `rmd` files using `styler::style_file()` function.
> feat(formatting): styler support rmd files

- lua/null-ls/builtins/_meta/diagnostics.lua
- lua/null-ls/builtins/_meta/filetype_map.lua
- lua/null-ls/builtins/_meta/formatting.lua
- lua/null-ls/builtins/diagnostics/puppet_lint.lua
- lua/null-ls/builtins/formatting/puppet_lint.lua
Based on the Rubocop formatter. This uses puppet-lint.
Signed-off-by: Jo Vandeginste <Jo.Vandeginste@kuleuven.be>
> Add diagnostics and formatter for Puppet

- doc/BUILTINS.md
- lua/null-ls/builtins/_meta/diagnostics.lua
- lua/null-ls/builtins/_meta/filetype_map.lua
- lua/null-ls/builtins/diagnostics/checkmake.lua
Adds diagnostics support for the checkmake tool (https://github.com/mrtazz/checkmake). This is something I've been using myself as a custom null-ls source for a while, formalized as a null-ls builtin.
> feat: Add support for checkmake tool

- doc/BUILTINS.md
- lua/null-ls/builtins/_meta/filetype_map.lua
- lua/null-ls/builtins/_meta/formatting.lua
- lua/null-ls/builtins/formatting/xmllint.lua
This is another custom source I've been using successfully for some time that I've reworked as a builtin. Although `xmllint` may not be a very well known tool, it's installed by default on many *nix systems as it's part of libxml2, and it works very smoothly for formatting.
> feat: Add xmllint for XML formatting

- lua/null-ls/builtins/diagnostics/statix.lua
I just found out that statix ​​doesn't work.
I have the latest statix ```Version: 0.5.2```
With this fix it works again.
> fix(diagnostics): statix

- lua/null-ls/utils.lua
- test/spec/utils_spec.lua
This utility makes it easier to work in polyglot monorepos. For instance, I may have a `.prettierrc` file I want to check for in a sub-directory rather than the root directory.
An alternative name for this function could be `cwd_has_file`. This is more convenient than `vim.loop.fs_stat(filename)` because it allows for tables like the `root_has_file` function, enabling the following:
```lua
local function prettier_condition(utils)
-- See https://prettier.io/docs/en/configuration.html
local files = {
'.prettierrc',
'.prettierrc.json',
'.prettierrc.yml',
'.prettierrc.yaml',
'.prettierrc.json5',
'.prettierrc.js',
'.prettierrc.cjs',
'.prettier.config.js',
'.prettier.config.cjs',
'.prettierrc.toml',
}
return utils.has_file(files) or utils.root_has_file(files)
end
local sources = { …
```
> Add has_file utility

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/astyle.lua
This is a simple file formatter that works well for Arduino files.
I also added filetypes `"c", "cpp", "cs", "java" ` as this formatter also supports them.
I tested this locally and it works well.
> Add support for builtin astyle.

- lua/null-ls/builtins/code_actions/statix.lua
Never version uses 1 to indicate possible fixes, fix should be backward compatible.
> Allow exit 1 for statix action

- lua/null-ls/builtins/formatting/prettier.lua
- lua/null-ls/builtins/formatting/prettier_d_slim.lua
- lua/null-ls/builtins/formatting/prettierd.lua
I was recently looking for a way to avoid showing diagnostic errors for comments in json files and found [this](https://www.reddit.com/r/neovim/comments/pfy8et/how_to_not_have_diagnostic_error_in_a_json_file/hb8t57j/?utm_source=share&utm_medium=web2x&context=3) way to fix it. 
TL;DR the fix consists in setting the filetype to jsonc (same conduct as vscode, json lsp continues working as usual), so I added jsonc in prettier filetypes.
> fix: add "jsonc" in prettier filetypes

- doc/BUILTINS.md
- lua/null-ls/helpers/command_resolver.lua
- lua/null-ls/helpers/generator_factory.lua
- lua/null-ls/loop.lua
- test/spec/loop_spec.lua
This PR is probably quite ugly, but I don't do a lot of Lua or Vim scripting normally.
I also couldn't get tests to work locally, but it seems `doc/TESTING.md` is out of date? There's a mention of a relative runtimepath, which I can only find in old versions of `minimal.vim`. I'm not sure where it is trying to find plenary and null-ls right now. I get output like:
```
Error detected while processing /src/contrib/null-ls/test/minimal.vim:
line    5:
E919: Directory not found in 'packpath': "pack/*/opt/plenary.nvim"
line    6:
E919: Directory not found in 'packpath': "pack/*/opt/null-ls.nvim"
line    8:
E5108: Error executing lua [string ":lua"]:1: module 'null-ls.config' not found:
[...]
```
What this PR does is add an extra lookup step to `from_node_modules` for finding executables …
> Add support for Yarn v2+ with PnP

- .github/workflows/default.yml
It looks like the stylua and selene checks are still not using cached downloads, and I suspect this is because PR builds can't populate the cache for security reasons. ([docs ref](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache))
CI is already plenty fast, it appears usually in the ~20s range. I expect this'll only save a second or two, so maybe a bit nitpicky. Also won't be able to tell if this works or not until it's on the main branch and someone opens a PR. 🤷
> fix: run CI checks on main branch

- lua/null-ls/builtins/diagnostics/golangci_lint.lua
The diagnostics from golangci-lint can be emitted from multiple linters. Including the value of FromLinter can help user identifies which linter emitted the specific message. Prior this change, a diagnostic message looks like:
```
don't use `init` function golangci-lint [15, 1]
```
With this change it will be:
```
don't use `init` function golangci-lint:gochecknoinits [15, 1]
```
Please let me know what you think or if there is anything I can do to improve this PR. Thank you.
> Include FromLinter in golangci-lint's source

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/autopep8.lua
added support for range format in autopep8 as mentioned in [this issue](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/711)
> added support for range format in autopep8

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/phpmd.lua
When writing code, you will naturally have syntax errors (before you have finished writing a line of code, for example).
Without this change, such errors will cause an error in null-ls:
```
lua/null-ls/helpers/generator_factory.lua:229: error in generator output
```
The PHPMD language server will stop working:
- any existing diagnostic messages will remain on the screen, even if you fix the relevant problem
- no new diagnostic messages will be shown
I believe this is because `phpmd` is exiting with a non-zero status code when it encounters syntax errors.  This change stops it from doing that.
> fix: prevent errors from killing PHPMD Language Server

- doc/HELPERS.md
- lua/null-ls/builtins/formatting/autopep8.lua
- lua/null-ls/builtins/formatting/format_r.lua
- lua/null-ls/builtins/formatting/prettier.lua
- lua/null-ls/builtins/formatting/prettier_d_slim.lua
- lua/null-ls/builtins/formatting/stylua.lua
- lua/null-ls/builtins/formatting/yapf.lua
- lua/null-ls/helpers/range_formatting_args_factory.lua
- lua/null-ls/utils.lua
- test/spec/helpers/range_formatting_args_factory_spec.lua
The current implementation of `range_formatting_args_factory` is too narrow, since it assumes that formatters always want separate arguments to define the start and end of the range and that they always use character offsets. This has led contributors to write their own versions to handle common cases like passing line numbers instead of offsets. This is fine but defeats the purpose of having the helper in the first place.
The PR should be fairly self-documenting, but the overall goal here was for the helper to handle the cases currently in the codebase and (hopefully) be flexible enough to handle future cases we haven't yet encountered. I also added test coverage and improved type annotations in a few places.
I tested the current built-ins and confirmed that they're all working (`yapf` …
> feat(helpers): generalize range_formatting_args_factory

- doc/BUILTINS.md
- lua/null-ls/builtins/_meta/diagnostics.lua
- lua/null-ls/builtins/_meta/filetype_map.lua
- lua/null-ls/builtins/diagnostics/djlint.lua
It was already configured as a formatter (missing from the docs) but it can also be used for diagnostics.
> Add djlint diagnostics

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/tidy.lua
Ensures that tidy diagnostics appropriate to XML files are shown, rather than HTML files.
Should close issue https://github.com/jose-elias-alvarez/null-ls.nvim/issues/754.
> fix(builtins): Add `-xml` parameter for XML files

- lua/null-ls/builtins/diagnostics/alex.lua
Ensures the builtins alex working. Otherwise neovim will print message
```
Error detected while processing /home/nkcfan/.config/nvim/init.vim:
line  106:
E5108: Error executing lua ...e/nkcfan/.vim/bundle/null-ls.nvim/lua/null-ls/sources.lua:208: fn: expected function, got nil
stack traceback:
[C]: in function 'error'
vim/shared.lua:608: in function 'validate'
...e/nkcfan/.vim/bundle/null-ls.nvim/lua/null-ls/sources.lua:208: in function 'validate_and_transform'
...e/nkcfan/.vim/bundle/null-ls.nvim/lua/null-ls/sources.lua:36: in function 'register_source'
...e/nkcfan/.vim/bundle/null-ls.nvim/lua/null-ls/sources.lua:279: in function 'register'
/home/nkcfan/.vim/bundle/null-ls.nvim/lua/null-ls/config.lua:103: in function 'setup'
/home/nkcfan/.vim/bundle/null-ls.nvim/lua/null-ls/init.lua:31: …
```
> fix(builtins): alex adds required factory entry

- lua/null-ls/builtins/diagnostics/phpmd.lua
- lua/null-ls/builtins/diagnostics/twigcs.lua
Due to [a bug](https://github.com/phpmd/phpmd/issues/941) in PHPMD, STDIN doesn't work on the current version unless you explicitly update its dependency, PDepend. (see https://github.com/pdepend/pdepend/pull/593).
This update to the builtin makes it use a temp file instead, meaning it will work with PHPMD without requiring the PDepend fix.
I have also removed the `--ignore-errors-on-exit` argument, because it isn't supported on older versions of PHPMD and we can instead handle non-zero exit codes in `check_exit_code` .
> fix(diagnostics): Compatibility with older versions of PHPMD work

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/solhint.lua
- test/spec/builtins/diagnostics_spec.lua
Closes #171.
Adding support for linting [Solidity](https://soliditylang.org/) files using [solhint](https://protofire.github.io/solhint/).
Changes include:
- solhint diagnostic builtin
- solhint documentation in BUILTINS.md
- solhint diagnostic tests
Tested with `solhint v3.3.7` on `Pop!_OS 21.10 x86_64` and `nvim v0.6.1`. Screenshot below showing an example of null-ls output with solhint via [trouble](https://github.com/folke/trouble.nvim).
> feat: adding solhint diagnostic support for solidity files

- lua/null-ls/builtins/diagnostics/sqlfluff.lua
- lua/null-ls/builtins/formatting/sqlfluff.lua
Add sqlfluff as a diagnosis and formatting option for sql files. (Thanks again for the help on the question answered the other day).
> feat: Add sqlfluff as sql format and diag source

- doc/BUILTINS.md
- lua/null-ls/builtins/_meta/diagnostics.lua
- lua/null-ls/builtins/_meta/filetype_map.lua
- lua/null-ls/builtins/diagnostics/fish.lua
`fish --no-execute $FILENAME` will give basic diagnostics for `.fish` files.
> feat: add fish --no-execute diagnostics

- lua/null-ls/diagnostics.lua
- test/spec/diagnostics_spec.lua
It can occur after (LSP) renaming the class without opening it (e.g. on its some reference).
> Do not set diagnostics for nonexisting buffer

- lua/null-ls/builtins/diagnostics/phpcs.lua
[PHPCS supports a `stdin-path` option](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage) to specify the path of the file passed to stdin.
> Use stdin-path option for phpcs

- lua/null-ls/builtins/formatting/bibclean.lua
bibclean is a fast fixer (and also linter) for BibTeX files, written in C. It is usually available on CTAN, but latest versions are available on the author's website.
> feat: Add bibclean formatter for BibTeX

- lua/null-ls/builtins/formatting/rome.lua
This adds support [Rome](https://rome.tools) formatting source.
> feat(builtin): Add `rome format` for javascript and typescript

- lua/null-ls/builtins/formatting/alejandra.lua
Alternative to `nixpkgs-fmt` and `nixfmt`.
> feat: add `alejandra` formatter for `nix`

- lua/null-ls/builtins/diagnostics/cspell.lua
- lua/null-ls/builtins/diagnostics/luacheck.lua
- lua/null-ls/builtins/diagnostics/selene.lua
- lua/null-ls/builtins/diagnostics/teal.lua
- lua/null-ls/builtins/diagnostics/write_good.lua
- lua/null-ls/helpers/diagnostics.lua
As mentioned in #821, all builtins that used end_col.from_quote added a manual offset of 1. This removes the need for that by offsetting the end_col in the helper itself.
This also removes the adapter from luacheck since no `_quote` field was parsed anyway.
> refactor(helpers): offset end_col.from_quote by 1

- lua/null-ls/builtins/diagnostics/solhint.lua
This fixes not seeing warnings/errors when running null-ls diagnostics on Solidity files. The change will now make diagnostic messages to actually show up in the proper output buffer.
Here is the `NullLsLog` output for said diagnostics in debug mode:
> fix: switching from_stderr to `false` for solhint diagnostics

- lua/null-ls/client.lua
- lua/null-ls/rpc.lua
- test/spec/client_spec.lua
Should fix #835. The specific issue is that the type of `textDocumentSync.save` doesn't match what Neovim expects. I think this is an upstream regression, since the specification indicates that a boolean value is acceptable:
But it's an easy fix on our end. I've also included a fix for the deprecation warning from accessing `client.resolved_capabilities` on 0.8.
Edit: tests will fail until there's a new nightly build, since the CI action doesn't build from source, but they're passing for me locally. I'd appreciate confirmation from anyone who commented on the original issue!
> fix: adapt to 0.8 breaking changes

- lua/null-ls/builtins/diagnostics/pylint.lua
The symbol attribute is used as a human-interpretable code in pylint,
for instance, "bad-indentation" for a error code W0311. (See:
https://pylint.pycqa.org/en/latest/technical_reference/features.html)
This additional metadata can be exported to as diagnostics entry,
so that users may include them in the diagnostics message.
> feat: Expose symbol attribute for pylint

- lua/null-ls/builtins/diagnostics/mypy.lua
The mypy builtin was not displaying some diagnostics due to failing to
parse them properly. The previously used regex pattern assumed that
each line in mypy's output would have a column number and a error code.
This is the case for most lines but not for all of them. For example the
following line contains no column number or error code:
```tests/slack_app/conftest.py:10: error: Unused "type: ignore" comment```
In this case null-ls would fail to display this error in the editor
because it could not be parsed. This commit fixes that issue by adding a
additional regex pattern that can parse lines in the format of the
example.
> Fix mypy builtin not displaying some diagnostics

- lua/null-ls/builtins/diagnostics/credo.lua
if the elixir project has warnings, the elixir compiler will first output
warnings on stderr, which are NOT in json format and break the credo
integration => ignore stderr for the credo integration.
> elixir credo integration: read stderr or stdout depending on output

- doc/BUILTINS.md
Those linters cannot correctly parse non-file arguments after the first
file is specified. This causes the extra_args feature of null-ls to not
work.
See discussion https://github.com/jose-elias-alvarez/null-ls.nvim/pull/399
> docs: document staticcheck and revive quirks

- lua/null-ls/builtins/completion/luasnip.lua
As currently configured, this completion source misses all snippets not directly added to the `snippets` table, including those loaded with [`require("luasnip.loaders.from_lua")`](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#lua) and those loaded with [`require("luasnip.loaders.from_vscode")`](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#vscode). Using `get_snippets` method gets all available snippets, including those loaded by other methods.
> fix: luasnip not getting all available snippets

- lua/null-ls/builtins/diagnostics/revive.lua
- lua/null-ls/builtins/diagnostics/staticcheck.lua
Those linters cannot correctly parse non-file arguments after the first
file is specified. This causes the extra_args feature of null-ls to not
work.
Seems like I put the notes in the wrong, old place in version 1 and they got overwritten by the auto-generation of the documents in this [commit](https://github.com/jose-elias-alvarez/null-ls.nvim/commit/82d5120c343b3e874da95946b1f6f1b79f72ae3b). Sorry for that sloppy mistake.
> docs: document staticcheck and revive quirks v2

- lua/null-ls/builtins/diagnostics/mypy.lua
- test/spec/builtins/diagnostics_spec.lua
See #893 for context. 
I think this should be fine - I'm not thrilled about adding another pattern, but I don't think Lua has a way to handle `code` as an optional capture group. I also added test coverage to clarify the cases we're currently handling and prevent regressions if someone wants to improve this in the future, since this source has already been through a few iterations.
> fix(builtins): handle mypy diagnostics without code

- doc/BUILTIN_CONFIG.md
- lua/null-ls/loop.lua
- test/spec/loop_spec.lua
When using the `buf` formatter, I was getting this error, and the formatter would fail to run:
```
[TRACE Tue 07 Jun 2022 06:41:45 PM MDT] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:217: error output: Failure: failed to enumerate module files: open /tmp/.<some_file_or_dir>: permission denied
```
I've made this modification locally as it seemed logical to use a per-user temp directory to address the issue. However, it could have been resolved similarly with subdirectories of `/tmp` as well.
> Support XDG_RUNTIME_DIR for temp_files

- lua/null-ls/builtins/diagnostics/flake8.lua
These are some commonly used plugins for flake8. It's tricky to customize the severities for them, and it doesn't hurt to have them here if they aren't installed, so might as well have them for folks that use them.
> add severities for common flake8 plugins

- lua/null-ls/builtins/formatting/blue.lua
Blue is an alternative formatter to black for python formatting.
> Add blue formatter as builtin

- lua/null-ls/builtins/diagnostics/cfn_lint.lua
- Added runtime_condition for cfn_lint diagnostics to only produce cfn-lint diagnostics when the file looks like an AWS Cloudfromation template.
- This prevents diagnostics from being run on all JSON and YAML files being edited.
**NOTE**
- @jose-elias-alvarez from our [discussion](https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/910) I found some behaviour which might not be as expected.
Screenshot of a YAML file where cfn-lint diagnostics are not being produced (the desired result), however the cfn-lint source still appears as attached. Not sure if this is expected.
Screenshot of adding `AWSTemplateFormatVersion` to the same YAML file, which then results in cfn-lint starting to produce diagnostics. I believe we were expecting the buffer cache to prevent cfn-lint from …
> feat: added default runtime condition for cfn_lint diagnostics source

- lua/null-ls/builtins/diagnostics/cfn_lint.lua
- Added stricter pattern matching for cfn-lint runtime_condition function when determining if a file is a cloud formation template or not.
- Based on the following implementation used for the vs-code extension https://github.com/aws-cloudformation/cfn-lint-visual-studio-code/blob/master/server/src/server.ts#L144
- This is not an exact match of this regex in the above link, the patterns in this PR have been modified slightly in some cases (shortened to use meta characters, being stricter by looking for an "AWS" prefix etc.)
- Screenshot of a cloud formation file with resource types defined under the Resources key (json).
- Screenshot of a cloud formation file with resource types defined under the Resources key (yaml).
- Screenshot of AWSTemplateVersionFormat being used to attach cfn-lint …
> fix: added stricter pattern matching for cfn-lint runtime_condition

- lua/null-ls/builtins/formatting/fourmolu.lua
I upgraded to Fourmolu 0.7.0.1 and it requires the `--stdin-input-file` argument when using stdin.
> Fix fourmolu formatting builitin

- lua/null-ls/builtins/diagnostics/stylelint.lua
Hi, thanks for making this awesome plugin!
I noticed `builtins.diagnostics.stylelint` does not look up local installations of Stylelint in `node_modules`.
I fixed it by using the `from_node_modules` command resolver like `builtins.formatting.stylelint` already does.
> fix: diagnostics.stylelint not using local binary

- doc/BUILTIN_CONFIG.md
- lua/null-ls/diagnostics.lua
- lua/null-ls/generators.lua
- lua/null-ls/helpers/make_builtin.lua
- test/spec/generators_spec.lua
This is a rough first pass at being able to filter diagnostic messages. Am I somewhere in the ballpark? 😅
I've been using it locally for the last couple weeks, seems to be working well. I was looking at adding unit tests but I was unable to get the e2e tests to pass locally. I figured I would get some feedback before I went too deep.
My vim config looks like this, with a new `diagnostics_filter` function parameter:
```
null_ls.setup({
on_attach = function(client)
if client.resolved_capabilities.document_formatting then
-- format on save
vim.cmd("autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting_sync(nil, 2000)")
end
end,
diagnostics_format = "[#{c}] #{m} (#{s})",
sources = {
null_ls.builtins.diagnostics.eslint_d.with({
diagnostics_filter = function(diagnostic)
if diagnostic.code == …
```
> WIP Filtering Diagnostic Messages

- lua/null-ls/builtins/diagnostics/glslc.lua
- test/spec/builtins/diagnostics_spec.lua
Shows the diagnostics provided by glslc when validating a shader.
It needs the shader stage for it to work, which is explained in the notes.
> feat: add glslc diagnostics

- lua/null-ls/builtins/diagnostics/cue_fmt.lua
It would appear that CUE moved from reporting format errors from `cue fmt` to `cue vet`.
Resolves https://github.com/jose-elias-alvarez/null-ls.nvim/issues/790
> fix: cue diagnostic

- lua/null-ls/builtins/formatting/packer.lua
Adds formatting for [Hashicorp Packer](https://www.packer.io/)
Ideally, I would like this to only target `.packer.hcl` files, but I'm unsure how to do this.
Currently, null-ls doesn't target `hcl` files, so this will not cause issues.
Would love feedback.
Thanks for null-ls.
> feat: add packer fmt

- lua/null-ls/builtins/diagnostics/actionlint.lua
Use `fnamemodify` to convert the forward slashes to backward slashes in Windows.
> fix: properly parse actionlint path for Windows

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/textlint.lua
I implemented textlint formatting with reference to #532 and [markdownlint](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/8c90ccf7ffbdeb49da415837ec45e6ac457d5c60/lua/null-ls/builtins/formatting/markdownlint.lua).
> feat(builtin): Add `textlint` formatting

- lua/null-ls/builtins/formatting/npm_groovy_lint.lua
Following couple of issues I created for npm-groovy-lint to accept stdout and single filenames:
https://github.com/nvuillam/npm-groovy-lint/pull/236
https://github.com/nvuillam/npm-groovy-lint/issues/227
npm-groovy-lint now works better with stdin and all.
Also, `Jenkinsfile` is a valid filetype for groovy formatting, this should be enabled by default.
Thanks!
> Use stdin for npm-groovy-lint and add filetype

- lua/null-ls/builtins/diagnostics/commitlint.lua
[commitlint](https://commitlint.js.org/) checks if your commit messages meet the conventional commit format.
this is a cli tool that doesn't return line numbers. so, i've done some formatting to try and prevent all warnings from showing up on line 0, column 0.
you'll need commitlint and the json formatter packages:
``` shell
yarn global add @commitlint/{config-conventional,cli} 
yarn global add commitlint-format-json
```
then create a `commitlint.config.js` in the root of your project:
``` javascript
const Configuration = {
extends: ["@commitlint/config-conventional"],
formatter: "commitlint-format-json",
rules: {
"header-max-length": [2, "always", 72],
"body-max-line-length": [2, "always", 72],
},
};
module.exports = Configuration;
```
also, you can override the config file with an …
> feat(commitlint): add diagnostics for commit messages

- lua/null-ls/builtins/diagnostics/spectral.lua
- test/spec/builtins/diagnostics_spec.lua
> A flexible JSON/YAML linter for creating automated style guides, with baked in support for OpenAPI v3.1, v3.0, and v2.0.
> feat(builtins): add support for spectral lint

- lua/null-ls/builtins/diagnostics/ktlint.lua
- lua/null-ls/builtins/formatting/ktlint.lua
This resolves issue #1044 by adding the default file patterns to the ktlint executable params. 
There's a info log that outputs if these are missing, so if we add these then that goes away. Since these are the default, adding them in is the same as not adding them in.
> Adds default file patterns to ktlint (#1044)

- lua/null-ls/builtins/diagnostics/phpcs.lua
When using a configuration file to configure the basepath, like for instance here: https://github.com/doctrine/collections/blob/c2a8c5f0f806cc467b1103a418db3e73815e83b6/phpcs.xml.dist#L3, no diagnostic appears.
Overriding it again in the CLI allows to get absolute paths, and fixes the issue.
> Enforce absolute paths in phpcs output 

- lua/null-ls/builtins/diagnostics/sqlfluff.lua
This is coming from #1054. 
While I don't know yet which part of the spawn / generator-factory leads to the output being ignored here,
but I definitely know that sqlfluff _does_ output to `stdout`.
And setting `from_stderr=false` solves the issue that diagnostics are not shown.
> fix sqlfluff diagnostics

- lua/null-ls/builtins/diagnostics/pycodestyle.lua
Add support for [pycodestyle](https://github.com/PyCQA/pycodestyle) which is is a tool to check your Python code against some of the style conventions in [PEP 8](http://www.python.org/dev/peps/pep-0008/).
> feat(diagnostics): add support for pycodestyle

- scripts/autogen.lua
BUILTINS.md is so large. So i add index to search easily nullls.buitinins.
```md
This is an automatically generated list of all null-ls built-in sources.
See [BUILTIN_CONFIG](BUILTIN_CONFIG.md) to learn how to set up and configure these sources.
- [Code Actions](#code-actions)
- [Completion](#completion)
- [Diagnostics](#diagnostics)
- [Formatting](#formatting)
- [Hover](#hover)
...
```
> feat(doc):add index in doc/BUILTINS.md

- lua/null-ls/builtins/diagnostics/tidy.lua
Add option -lang en to the call to tidy to get right output.
Fix #1064
> fix(builtins): fix tidy diagnostics lang spec

- lua/null-ls/builtins/hover/printenv.lua
Shows the value for the current environment variable under the cursor.
This source is similar in function to `printenv` where it shows value of environment variable, however this source uses `vim.fn.environ()` instead of `printenv` thus making it cross-platform.
> feat(hover): add support for printenv

- lua/null-ls/builtins/diagnostics/cpplint.lua
[cpplint](https://github.com/cpplint/cpplint) support, which mentioned at https://github.com/jose-elias-alvarez/null-ls.nvim/issues/508
Tested with `cpplint` that installed by `brew` and [`Mason`](https://github.com/williamboman/mason.nvim)
Preview:
> feat(diagnostics): add cpplint

- lua/null-ls/utils.lua
- test/spec/utils_spec.lua
Reverts jose-elias-alvarez/null-ls.nvim#1017. @jceb 
I believe this is the cause of the issues described in #1047, though I don't know exactly why. If I had to guess, I'd say that `vim.fn.resolve` and `vim.fn.exepath` have different behavior on different platforms, so one potential alternative  would be to use libuv's [fs_realpath](https://github.com/luvit/luv/blob/master/docs.md#uvfs_realpathpath-callback). Either way, I think it's safest to revert this for now.
> Revert "fix(utils): resolve symlinks before testing executable bit"

- lua/null-ls/builtins/code_actions/eslint.lua
- lua/null-ls/builtins/diagnostics/eslint.lua
- lua/null-ls/builtins/diagnostics/puglint.lua
- lua/null-ls/builtins/diagnostics/standardjs.lua
- lua/null-ls/builtins/diagnostics/stylelint.lua
- lua/null-ls/builtins/diagnostics/stylint.lua
- lua/null-ls/builtins/formatting/eslint.lua
- lua/null-ls/builtins/formatting/prettier.lua
- lua/null-ls/builtins/formatting/prettier_d_slim.lua
- lua/null-ls/builtins/formatting/prettier_standard.lua
- lua/null-ls/builtins/formatting/prettierd.lua
- lua/null-ls/builtins/formatting/rescript.lua
- lua/null-ls/builtins/formatting/rustywind.lua
- lua/null-ls/builtins/formatting/standardjs.lua
- lua/null-ls/builtins/formatting/stylelint.lua
- lua/null-ls/helpers/command_resolver.lua
- lua/null-ls/helpers/make_builtin.lua
Follow-up to #1063. I tried to avoid breaking the signature of existing command resolvers, but the structure wasn't compatible with the `by_bufnr` cache helper. 
This change means that anyone using `from_node_modules` or `from_yarn_pnp` directly needs to update their usage a bit:
```lua
local null_ls = require("null-ls")
local command_resolver = require("null-ls.helpers.command_resolver")
local prettier = null_ls.builtins.formatting.prettier.with({
-- old
-- dynamic_command = command_resolver.from_node_modules,
-- new
dynamic_command = command_resolver.from_node_modules(),
})
```
> fix!: update command resolver signature to fix caching

- README.md
- lua/null-ls/health.lua
- lua/null-ls/helpers/generator_factory.lua
- lua/null-ls/loop.lua
- lua/null-ls/utils.lua
- test/spec/helpers/generator_factory_spec.lua
- test/spec/loop_spec.lua
- test/spec/utils_spec.lua
Supersedes #892. The purpose of that PR was to improve messaging in dynamically-resolved `node_modules` commands. This PR implements the approach I described in a comment:
> If you're up for it, a more robust solution might be to determine the ability to execute a command based on the result of vim.loop.spawn, since vim.fn.executable doesn't account for all cases. Neovim switched to this approach for LSP servers in https://github.com/neovim/neovim/pull/16430, and I've been meaning to switch over to it, too (except for healthchecks).
This should also improve the situation that #1017 was intended to fix, since null-ls doesn't have to check whether a command is executable before attempting to spawn it. @jceb Could you check if this works for you when using symlinks?
Unfortunately, this …
> feat(loop): check if command is executable by handling spawn failure

- lua/null-ls/helpers/generator_factory.lua
- lua/null-ls/loop.lua
- test/spec/helpers/generator_factory_spec.lua
- test/spec/loop_spec.lua
Discussed in #1069. @andrewferrier 
Our current temp file creation mechanism uses a dedicated temporary directory (`$TEMP` on Windows, `$XDG_RUNTIME_DIR` if set, and `/tmp` otherwise). The issue, which has come up before, is that some linters / formatters use file paths to resolve config files. Well-behaved CLIs like [`black`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/black.lua) use an additional flag to specify the "actual" filepath, even when using `stdin`, but we can't expect this behavior for all CLIs (using a temp file is itself a hack to improve behavior when `stdin` is not supported).
I resisted making this change in the past because I didn't like the idea of writing to an actual project, even temporarily, and I worried about …
> feat(loop): create temp files at source location

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/sqlfluff.lua
The previous behaviour had null-ls pass in the contents of a SQL file to stdin. This doesn't work if the user has created a local .sqlfluff file (for example to specify the dialect), as sqlfluff cannot tell where the file is on the filesystem. This commit changes that behaviour.
> fix(builtins): allow use of local .sqlfluff file

- doc/BUILTIN_CONFIG.md
- doc/CONFIG.md
- lua/null-ls/diagnostics.lua
- lua/null-ls/helpers/make_builtin.lua
- test/spec/e2e_spec.lua
Closes #1094. @mikatpt
null-ls uses separate diagnostic namespaces per source, which is a prerequisite for multiple-file diagnostics but makes configuration annoying. One option is to allow configuring source namespace generation (or expose existing namespaces more readily), but this increases the chances of collisions and unexpected behavior. 
This PR instead configures source namespaces using the `diagnostic_config` key when the namespace is first generated. The option is available per-source and globally, since null-ls' unique behavior means that there is currently no good way to configure the display of all null-ls diagnostics.
> feat(builtins): allow configuring diagnostics display

- lua/null-ls/builtins/formatting/mix.lua
This allows the mix format command to correctly format non-elixir files, such as heex templates.
> Add --stdin-filename to mix formatter

- lua/null-ls/loop.lua
- test/spec/loop_spec.lua
Since #1075, null-ls has been creating temp files at the same path as the actual file. So far, we haven't received any bug reports (knock on wood) so I'd say the change is a definite improvement - for example, in #1107 we are using it to allow the linter to resolve its config file without user intervention - but it has some drawbacks.
In the same issue, a user discussed how the constant creation and deletion of temp files causes nvim-tree to shrink and expand, a minor visual issue solved by making the file hidden (at least on Unix).
At some point, an issue may arise that forces us to make this configurable and potentially even default to `/tmp` again, but I'd like to wait until that happens before making further changes, since I'm happy with the current state of things, both from a …
> fix(loop): use . prefix to make temp files hidden

- lua/null-ls/generators.lua
- test/spec/generators_spec.lua
Follow up to #1048. The goal of deep copying the `params` table is to prevent accidentally leaking changes between different generators, an issue that has come up in the past. I considered using a metatable to make the object itself immutable, but I think this would be worse for performance, and it's not unreasonable for a given generator to modify its own `params` (plus I suspect it would break a bunch of sources that are already doing so). 
The effect of running `vim.deepcopy` is only measurable in nanoseconds, but it does grow as `params` grows larger, and this is an easy optimization to handle the most common case, which is a single generator per method.
> perf(generators): only deep copy params when needed

- lua/null-ls/loop.lua
Fixes an issue raised in #1075. Temp file-based generators created using `generator_factory` will only call `cleanup` on `stdout` end, so if the user exits Neovim after a generator has started running but before it's done, `cleanup` will not be called. This PR hooks into `VimLeavePre` to ensure that `cleanup` is called in this edge case (shout out to the autocommand API, without which this would have been a pain). 
@soifou I tested this using artificial delays / conditions, but could you give this a try and let me know if it solves the issue for you?
> fix(loop): clean up temp files on exit

- lua/null-ls/builtins/diagnostics/pylint.lua
Pylint diagnostics show with the correct start column, but the end column is off by one; this fixes it.
> fix(pylint): offset end_col as well

- lua/null-ls/builtins/formatting/yamlfmt.lua
yamlfmt supports `stdin` via `-` since release [v0.3](https://github.com/google/yamlfmt/releases/tag/v0.3.0).
> fix(builtins): prefer stdin over temp file for yamlfmt

- lua/null-ls/builtins/code_actions/ltrs.lua
- lua/null-ls/builtins/diagnostics/ltrs.lua
Adding support for LanguageTool. LanguageTool is an online service to help you to correct blocks of text. It is a writing assistant, quite similar to other services like Grammarly.
More info: https://languagetool.org/
I think it can be handy to have an integration in NeoVim to help people to write better documentation, commit messages, etc.
This integration is performed thanks to [languagetool-rust](https://github.com/jeertmans/languagetool-rust/). A Rust implementation that interact with LanguageTool API.
This Null-ls Builtin adds diagnostics and code actions capabilities.
Some screenshots:
> diagnostics: add LanguageTool support (by ltrs)

- lua/null-ls/builtins/formatting/ocamlformat.lua
I've made a small PR to add ocamlformat as formatter for null-ls.
Right now it can already format every ocaml file with the default settings, just need some time to dig in the docs 
(https://github.com/ocaml-ppx/ocamlformat/blob/main/ocamlformat-help.txt) to support .ocamlformat.
> support for ocamlformat

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/haml_lint.lua
Should fix #1144 
Added generator option `to_temp_file = true` and notes for `haml_lint` builtin diagnostics.
> fix(builtins): haml_lint - add to_temp_file = true and notes

- lua/null-ls/builtins/diagnostics/mypy.lua
- lua/null-ls/builtins/formatting/isort.lua
Mypy needs `cwd` to discover the configuration file (https://mypy.readthedocs.io/en/stable/config_file.html)
Isort will detect files in the CWD as first-party (https://github.com/PyCQA/isort/blob/fa2de4761040a9fd82339fccc7cc42391eb082cf/CHANGELOG.md?plain=1#L434),
So although `setup.py` doesn't contain `isort` configuration, it helps `isort` sort correctly.
> fix(builtins): refine 'cwd' for mypy and isort

- lua/null-ls/builtins/formatting/prettier.lua
- lua/null-ls/builtins/formatting/prettier_d_slim.lua
- lua/null-ls/builtins/formatting/prettier_standard.lua
- lua/null-ls/builtins/formatting/prettierd.lua
The Prettier filename variants `prettier.config.js` and `prettier.config.cjs` were incorrectly prefixed with a dot which is not what Prettier expects.  This renames them to the proper non-dot prefix filenames.
> Fix filename for `prettier.config.js` variants

- README.md
- doc/CONFIG.md
I think it will be better for setup to be consistent with the rest of the docs, copy/pasting from [BUILTINS.md](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md) will also be easier
> refactor(docs): more consistent setup docs

- doc/BUILTIN_CONFIG.md
- doc/CONFIG.md
- lua/null-ls/config.lua
- lua/null-ls/helpers/generator_factory.lua
- lua/null-ls/helpers/make_builtin.lua
- lua/null-ls/loop.lua
- test/spec/helpers/generator_factory_spec.lua
- test/spec/loop_spec.lua
See #1075 for context and discussion. The previously raised issues were cosmetic, but #1223 raises a deeper issue (the kind that I expected to arise at some point).
This PR makes the directory in which temp files are created configurable globally and per-source, which should solve the issues that have been raised so far. I do believe that maintaining the current default makes sense, since any temp file-related issues are either bugs that we need to fix or bad interactions with integrations that are beyond our control. The PR also updates some outdated documentation.
Of course, this PR doesn't solve the fundamental issue that some sources *require* temp files to exist within a project for context, but that's something that has to be solved upstream.
> feat(builtins): allow overriding temp dir

- lua/null-ls/utils.lua
- test/spec/utils_spec.lua
Implemented the functionality discussed in #1225
I added some unit tests following the format of the previous conditional utils but for some reason it fails. I printed out the table that I get from this line ```local utils = u.make_conditional_utils()``` in ```utils_spec.lua``` and it doesn't include the ```root_has_file_matches``` function for some reason. I'm not sure what that is about haha.
Edit: Of course it passes in here haha, weird.
> feat: add ability to root file match to conditional utils

- lua/null-ls/builtins/formatting/rome.lua
This PR adds local-first resolving order for Rome formatter. I'd argue this should be the default since [Rome docs](https://docs.rome.tools/guides/getting-started/) guide users towards installing Rome to project dependencies.
> Resolve rome executable from node modules

- doc/CONFIG.md
- lua/null-ls/config.lua
- lua/null-ls/info.lua
This commit closes #1197 .
The border option was added to the config, and its possible to set it with the same parameters as nvim_open_win() border.  
Added highlight groups:
- `NullLsInfoHeader` Window header
- `NullLsInfoTitle`      Titles
- `NullLsInfoBorder`  Window border
- `NullLsInfoSources` Sources names
Docs were changed to reflect the new config options.
Example of the `border = "rounded"` option:
> feat: Make window border and window highlight of NullLsInfo configurable

- lua/null-ls/builtins/diagnostics/dotenv_linter.lua
Resolves #1252 .
@jose-elias-alvarez commit should be completely done, but I don't know how to make the source just attach to ".env" files.
Nvim sets filetype "sh" for all files and obviously having the source attach to every shell script buffer (as it currently does) is not desirable. Any tips?
> feat(dotenv-linter): add diagnostics

- lua/null-ls/builtins/diagnostics/ansiblelint.lua
Ansiblelint does not accept input from stdin, so either the null-ls builtin needs to use `methods.internal.DIAGNOSTICS_ON_SAVE` to run ansiblelint on save or it needs to use `to_temp_file` so the buffer content is written to a temporary file on which ansiblelint can run. Otherwise ansiblelint always runs on the previous modification. Ansiblelint is fast enough so `to_temp_file` works well, but it changes the filename in the diagnostic. In combination with `multiple_files` that means that diagnostics do not show up. `multiple_files` seemed unnecessary anyway so removing it should not cause problems.
> fix(builtins): keep ansiblelint in sync

- lua/null-ls/builtins/formatting/emacs_scheme_mode.lua
Not the nicest way, but I find emacs still to be the best formatter (in terms of the style).
A couple things to point out which aren't that nice:
- I couldn't get emacs to read a `.dir-locals.el` file to set local variables, because it is likely to have 'not safe' variables which need user confirmation. When running in batch mode emacs automatically declines loading a `.dir-locals.el` file
- Thus, when a user wants to adjust some settings, for example use tabs instead of spaces, then he needs to adjust the `args` field and replace the whole elisp code.
Formatting of VHDL in emacs: #1265
> feat(builtins): add scheme formatter (emacs in batch mode)

- lua/null-ls/builtins/formatting/emacs_vhdl_mode.lua
Not the nicest way, but I find emacs still to be the best formatter (in terms of the style).
A couple things to point out which aren't that nice:
- I couldn't get emacs to read a .dir-locals.el file to set local variables, because it is likely to have 'not safe' variables which need user confirmation. When running in batch mode emacs automatically declines loading a .dir-locals.el file
- Thus, when a user wants to adjust some settings, for example use tabs instead of spaces, then he needs to adjust the args field and replace the whole elisp code.
Formatting of scheme in emacs: #1264
> feat(builtins): add VHDL formatter (emacs in batch mode)

- doc/CONTRIBUTING.md
- lua/null-ls/health.lua
- lua/null-ls/helpers/make_builtin.lua
- lua/null-ls/sources.lua
(Attempts) to solve [this](https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/1215) issue.
Currently:
After PR:
While the functionality works I'm curious on your input on the actual language of the healthcheck itself. Let me know what you think or if there's a clearer way to get the point across.
Also, if this gets merged I already have PRs ready for gitsigns and gitrebase to exploit this new functionality.
> feat: let sources define executable check functions

- lua/null-ls/builtins/formatting/codespell.lua
Fix #1279
Reference: https://github.com/codespell-project/codespell/issues/2633
> Fix codespell can't format

- lua/null-ls/builtins/diagnostics/golangci_lint.lua
Hello
Hello, I am using golangci-lint version 1.50.1 and discovered a bug: `golangci-lint run` doesn't accept any positional arguments, only options.
So current builtins `args` are causing linter to fail because `$DIRECTORY` is used as a positional argument.
I am not sure if this error existed always or this is caused by golangci changed its behaviour at some version.
2nd inconsistency is when linter fails - there weren't any notifications or logs from this builtin, so I've added a warning.
> fix for builtin golangci linter

- lua/null-ls/formatting.lua
[apply_text_edits is setting buflisted to true](https://github.com/neovim/neovim/blob/8b84a10db76ef2bd15bbd3c06ae2d5dfaadc1482/runtime/lua/vim/lsp/util.lua#L404), which causes the temporary buffer to be visible in bufferline.nvim for a split second
> fix: set buflisted to false after apply_text_edits

- doc/CONTRIBUTING.md
- lua/null-ls/builtins/code_actions/gitrebase.lua
- lua/null-ls/builtins/code_actions/gitsigns.lua
Here I add executable check functions for girebase and gitsigns, along with some documentation.
Before:
After:
and when not installed:
> feat(health): document, add executable check functions

- lua/null-ls/builtins/code_actions/cspell.lua
Currently when choosing the option "Add to cspell json file" and no json file exists, a file of the name `cspell.json` will be created. Since I always use `.cspell.json` I would want a way to always use that name instead.
> Option to change the default cspell json file name

- lua/null-ls/builtins/code_actions/gomodifytags.lua
`gomodifytags` code actions currently hard coded binary path and does don't support customization from `generator_opts`
Make a simple `factory` wrapper around current `generator` object to accept resolved generator opts
This PR does not change behavior of the current code actions. Only add additional layer for customization
> fix(gomodifytags): make gomodifytags more flexible

- lua/null-ls/builtins/formatting/hclfmt.lua
> Add HCL configuration formatting builtin support

- lua/null-ls/builtins/diagnostics/cpplint.lua
Fixes the situation where header order warnings returned by `cpplint` cannot be fixed because `null-ls` calls the linter on a generated temp file. More details in this [discussion](https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/1300).
It seems there are multiple messages that `cpplint` can return based on improper order of headers in a file, but they are all labelled as `build/include_order`, code [here](https://github.com/cpplint/cpplint/blob/fa12a0bbdafa15291276ddd2a2dcd2ac7a2ce4cb/cpplint.py#L5147).
This PR checks if the returned message from `cpplint` has severity `build` and label `include_order` and filters the message out  if it does.
Fixes #1351
> fix: filter out permanent cpplint header order warnings

- lua/null-ls/builtins/diagnostics/golangci_lint.lua
First, thanks for null-ls! I've found it to be super helpful.
I spent a good amount of time trying if/why debug if null-ls wasn't working and why I would see no errors via golangci-lint. I turned on debug mode for null-ls and tracked down the problem, the `--fast` flag disables a significant amount of the linters it provides, so the feedback in vim is different from other editors (like vscode) and the golangci-lint CLI output (omitting `--fast`).
This change removes `--fast` from the default arguments for `golangci-lint`. To get the old behavior back, you can use the `extra_args` argument when configuring `golangci-lint`. e.g.
```lua
null_ls.builtins.diagnostics.golangci_lint.with({
extra_args = { "--fast" },
}),
```
Since it's easier to add extra flags, and this isn't a default flag for …
> Remove --fast default from golangci-lint

- lua/null-ls/builtins/diagnostics/editorconfig_checker.lua
Hello,
There have been a few discussions around the name of the command that runs when using this source.
- https://github.com/williamboman/mason.nvim/pull/722
- https://github.com/jay-babu/mason-null-ls.nvim/issues/37
This tool currently runs a command call `ec`, which is not the default name of the tool when installed.
https://github.com/editorconfig-checker/editorconfig-checker
after installing using one of the methods described in the repo, I get a tool named: `editorconfig-checker` unless I do some special tinkering to make it work with the `null-ls` wants it. This change now adheres to the standard name of the tool.
> fix(builtins)!: modify editorconfig-checker to run using standard tool name

- lua/null-ls/utils/init.lua
- test/spec/utils/utils_spec.lua
In https://github.com/jose-elias-alvarez/null-ls.nvim/commit/f1182c2d3748da7c94f5288f8054741f26f0cf3b the function was changed from using `M.search_ancestors` which first checked the `start_path` and then the ancestors, to a `vim.fn.parents` iteration which does not include the `start_path` check anymore.
This PR adds a check for the `start_path` first (like it was before that commit) and then does the `vim.fn.parents`.
> fix: utils.root_pattern not checking the start_path for patterns

- lua/null-ls/builtins/formatting/erb_format.lua
Adds a built-in formatter to support `erb-formatter` to handle embedded Ruby files (https://github.com/nebulab/erb-formatter)
`erb-formatter` seems to produce much better results than `erb_lint`.
> feat(builtins): add erb-formatter support

- lua/null-ls/builtins/diagnostics/chktex.lua
In the latest chktex commits, chktex also produces exit codes 2 and 3 if there are errors and warnings. The Debian package (and its derivates) have already backported this change to their newest version.
Fixes: #1390
Ref: http://git.savannah.nongnu.org/cgit/chktex.git/commit/?id=ec0fb9b58f02a62ff0bfec98b997208e9d7a5998
> fix(chktex): Support exit codes for newer version

- lua/null-ls/builtins/diagnostics/ansiblelint.lua
- test/spec/builtins/diagnostics_spec.lua
ansible-lint will include lint results from included/imported task files.
```yaml
- name: Ping
ping:
- name: Include other task
include_tasks: baz.yml
```
```yaml
- name: Some lint results here
set_fact:
foo: yes
```
ansible-lint result:
```bash
ansible-lint -P=basic -f codeclimate -q roles/foobar/tasks/main.yml | jq
[
{
"type": "issue",
"check_name": "yaml[truthy]",
"categories": [
"formatting",
"yaml"
],
"severity": "info",
"description": "truthy value should be one of \\[false, true]",
"fingerprint": "8564f80bca9d93054e646e7ec5cfe5ee2c279b821ca183183c79d055bc062b8d",
"location": {
"path": "roles/foobar/tasks/baz.yml",
"lines": {
"begin": 3
}
}
}
]
```
ansible-lint was run against **main.yml** but the result was from **baz.yml**, which will result in a confusing floating text in nvim: …
> fix(builtins): handle extra files in ansible-lint results

- lua/null-ls/client.lua
null_ls.client.on_source_change is called upon null_ls.setup() or
enabling null-ls, but this method can often be slow and blocking
when searching all the existing buffers and trying to register
conditional sources, especially when their conditions may do some
slow I/O operations (e.g., file existence check).
Scanning all the existing buffers is also done over non-file buffers,
including terminal or nofile (temporary) buffers, which is not necessary
because they usually don't have any files associated with.
Skipping those buffers when trying to register sources will make
null-ls initialization performance much faster; in particular,
rendering of terminal buffers that are open before null_ls is loaded
will no longer stall.
> perf(client): Make conditional source registration faster

- lua/null-ls/builtins/diagnostics/verilator.lua
Fix the builtin verilator config not capturing Error information.
> Verilator: Fix Error Not Captured

- lua/null-ls/builtins/formatting/dprint.lua
The current dprint config only works when dprint is installed globally (and present on PATH). So, it does not work when dprint is locally installed with some Node.js's package manager (ex: `npm i -D dprint`).
This PR sets the `dynamic_command` option on the dprint formatter to allow that (I just copied/pasted from the prettier config :yum: ).
> feat(builtins): allow using dprint bin from node_modules

- lua/null-ls/builtins/formatting/crystal_format.lua
Crystal formatting is broken as `crystal tool format` by default formats files in-place.
To format stdout (as null-ls expects), one needs to add an argument `-`. That way `crystal tool format` reads from stdin and writes to stdout.
> Fix crystal formatting

- lua/null-ls/builtins/diagnostics/ansiblelint.lua
- test/spec/builtins/diagnostics_spec.lua
This is in reference to #1381, this adds the same changes (using the 'description' field of ansiblelint as message and the 'check_name' field as code).
I'm not sure if I'm using the `code` property correctly.
The tests have also been modified accordingly.
> fix(ansiblelint): Use 'description' and 'check_name' field

- lua/null-ls/builtins/formatting/ocamlformat.lua
Before, it was not overwriting the original file for some reason.
> Fix ocamlformat not overwriting

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/rubocop.lua
I encountered an error message stating
`'--auto-correct' is deprecated and should be replaced with '--autocorrect'`
It's due to Rubocop v1.30.0 where 'auto-correct' became a duplicate and was replaced with 'autocorrect'. 
https://github.com/rubocop/rubocop/pull/10547
Therefore, I have made the necessary correction to the code to use '--autocorrect' instead."
> fix(rubocop): change auto-correct to autocorrect

- lua/null-ls/builtins/code_actions/gomodifytags.lua
vim.treesitter.get_node_at_pos() is deprecated, use vim.treesitter.get_node() instead.
https://neovim.io/doc/user/deprecated.html
> fix(gomodifytags): remove deprecated vim.treesitter.get_node_at_pos

- lua/null-ls/builtins/formatting/djhtml.lua
I believe with the new 3.0 upgrade ( https://github.com/rtts/djhtml ) the expected command line arguments changed. 
After the upgrade, this was definitely broken, and adding this `arg` fixes it.
> fix `djhtml` formatter to support new version

- lua/null-ls/builtins/diagnostics/bslint.lua
Sorry I missed this when I first added the code.
> fix: bslint extra whitespace in message removed

- lua/null-ls/builtins/diagnostics/eslint.lua
- test/spec/builtins/diagnostics_spec.lua
This populates the user_data field with information regarding if the diagnostic is fixable or not, allowing you to filter out fixable or non fixable issues.
Closes https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1441.
> fix: populate user data for eslint

- lua/null-ls/builtins/diagnostics/pylint.lua
- test/spec/builtins/diagnostics_spec.lua
Similar to flake8, determine the `cwd` based on the pylint configuration files that it can find using `null-ls.utils.root_pattern`.
I tested this manually by moving the pyproject.toml and .flake8 config files around and comparing both. It seems to all work as expected. I also added some tests for pylint.
Any comments on the PR and tests would be appreciated.
> fix(builtins/diagnostics/pylint): set the cwd according to the config files

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/checkmake.lua
It appears that due to the format specified for `checkmake` (missing newline character at the end of each line), all diagnostic messages are provided to `null-ls` on a single line, instead of several lines.
Before:
WIth fix:
> fix(builtins): Separate diagnostic messages for 'checkmake' linter

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/rubyfmt.lua
This adds the Rust-based [rubyfmt](https://github.com/fables-tales/rubyfmt) formatter as a built-in to null-ls.
> Add rubyfmt formatter to built-ins

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/sqlfmt.lua
This adds the [sqlfmt](https://sqlfmt.com/) formatter as a built-in to null-ls.
> Add sqlfmt formatter to built-ins

- lua/null-ls/builtins/code_actions/gomodifytags.lua
Before all type identifiers were detected as struct declarations. This led to the next problems:
* declarations of other types were always struct declarations;
* using types for fields were detected the same way.
> fix(gomodifytags): detect struct type declaration

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/goimports_reviser.lua
Removed the deprecated -file-path arg and moved $FILENAME to the end as suggested. https://github.com/incu6us/goimports-reviser/commit/979c6e70f1b9dd25a30af74d8ae3efd4205a1bd2
EDIT: based on the discussion #1472, using temp file for now, till the issue with `stdin` gets resolved upstream.
> fix(goimports_reviser): remove the deprecated -file-path arg

- doc/BUILTINS.md
- lua/null-ls/builtins/_meta/code_actions.lua
- lua/null-ls/builtins/_meta/filetype_map.lua
- lua/null-ls/builtins/code_actions/gomodifytags.lua
- lua/null-ls/builtins/code_actions/impl.lua
Add `impl` tool, that generates interface implementation stubs in go language. To use it: 
1. Place your cursor on a name in type declaration:
```go
type |S struct{}
```
2. Run code action: `impl: implement interface`;
3. Input interface name in format `package.Interface`, for example, `io.Reader`;
4. Stub will be generated after the type declaration or after the last method of the type.
The code action tool chooses receiver name automatically based on another receiver names of type methods or generates it from the first letter of receiver type lowercased (idiomatic go way). Receiver type is chosen automatically too: pointer or not.
> feat(builtins/code_actions): add impl

- lua/null-ls/builtins/diagnostics/markdownlint.lua
- lua/null-ls/builtins/diagnostics/markdownlint_cli2.lua
- test/spec/builtins/diagnostics_spec.lua
I think, the error severity is too strict for markdown issues. This PR relaxes it to warning.
> fix(builtins/diagnostics/markdownlint): change severity to warning

- lua/null-ls/builtins/_meta/filetype_map.lua
- lua/null-ls/builtins/_meta/formatting.lua
- lua/null-ls/builtins/formatting/fantomas.lua
Mentioned in https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1489 this is to add F# formatter [Fantomas](https://github.com/fsprojects/fantomas).
Both [filetype_map.lua](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/_meta/filetype_map.lua) and [_meta/formatting.lua](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/_meta/formatting.lua) are marked as _DO NOT EDIT MANUALLY_. I don't see these in other accepted PRs either.
Then how do I generate the lines in those two files? Without these, the formatter doesn't work.
> feat(builtins/formatting/fantomas): A formatter for F#

- doc/BUILTINS.md
- lua/null-ls/builtins/_meta/diagnostics.lua
- lua/null-ls/builtins/_meta/filetype_map.lua
- lua/null-ls/builtins/diagnostics/terraform_validate.lua
- lua/null-ls/builtins/diagnostics/tfsec.lua
The formatter [lua/null-ls/builtins/formatting/terraform_fmt.lua](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/f8ffcd7cb8fb3325c711d459152ef132b5b65aed/lua/null-ls/builtins/formatting/terraform_fmt.lua#L13) already had these extra filetypes set.
> Enable additional filetypes for Terraform files

- lua/null-ls/builtins/diagnostics/clazy.lua
clazy can sometimes output fatal errors, for example when a file doesn't exist:
```
main.cpp:1:10: fatal error: 'non-existent' file not found
#include <non-existent>
^~~~~~~~~~~~~~
1 error generated.
```
These weren't caught by the regex and that resulted in 'msg' being nil.
Fix this by allowing a space when parsing the severity.
> fix(builtins/diagnostics/clazy): Handle fatal errors

- lua/null-ls/builtins/diagnostics/selene.lua
selene does no search for selene.toml and only finds it if it's in the $PWD
I tested interactively, and with this change selene is always properly configured.
> help selene find its config

- lua/null-ls/builtins/diagnostics/todo_comments.lua
Fixes issue #1527. Same reproduction steps with this patch does not produce the syntax bug.
I also created a separate bug with nvim-treesitter about the syntax breaking when `get_parser` is called with an invalid lang: https://github.com/nvim-treesitter/nvim-treesitter/issues/4693
> fix(builtins/diagnostics/todo_comments): convert filetype to lang before calling vim.treesitter.get_parser

- lua/null-ls/builtins/diagnostics/todo_comments.lua
This fixes a string concat with a nil value, if the current file type does not have a language registered with treesitter.
> fix(builtins/diagnostics/todo_comments): fix nil access

- lua/null-ls/health.lua
health api was changed in [#22927](https://github.com/neovim/neovim/pull/22927)
```help
- *health#report_error* *vim.health.report_error()*	Use |vim.health.error()| instead.
- *health#report_info* *vim.health.report_info()*	Use |vim.health.info()| instead.
- *health#report_ok* *vim.health.report_ok()*		Use |vim.health.ok()| instead.
- *health#report_start* *vim.health.report_start()*	Use |vim.health.start()| instead.
- *health#report_warn* *vim.health.report_warn()*	Use |vim.health.warn()| instead.
```
> fix(health): update to use new api

- lua/null-ls/builtins/code_actions/cspell.lua
Discussed in https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1466
With this hook, users can do whatever they like with cspell_config_file, such as beautifying the config file.
```lua
null_ls.builtins.code_actions.cspell.with({
config = {
find_json = function(_)
return vim.fn.expand("~/.config/nvim/cspell.json")
end,
on_success = function(cspell_config_file)
os.execute(
string.format(
"cat %s | jq -S '.words |= sort' | tee %s > /dev/null",
cspell_config_file,
cspell_config_file
)
)
end,
},
}),
```
https://github.com/keaising/dotfile/blob/553612b8c5b8456e10bfcf588a7f1c4787f2adb8/nvim/.config/nvim/lua/plugins/lsp.lua#L108-L116
> feat(builtins/code_actions/cspell): add `on_success` hook to cspell (#1466)

- doc/HELPERS.md
When reading the following source code, it assigns to `params.output`.
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/33b853a3933eed3137cd055aac4e539e69832ad0/lua/null-ls/helpers/generator_factory.lua#L304-L306
> docs: fix from_temp_file option for generator_factory helper

- lua/null-ls/builtins/diagnostics/golangci_lint.lua
This PR adds [multiple_files](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/376) support for the `golangci_lint` builtin. The current implementation runs the linter on the entire project, but due to the `if d.Pos.Filename == params.bufname then` condition the other diagnostics are filtered out. Removing that guard and adding the `multiple_files` flag allows displaying all the diagnostics which are already being generated by the command.
> Add multiple_files support to golangci_lint builtin

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/golangci_lint.lua
Hi,
I had issues trying to get golangci-lint to work in a monorepo.
I believe this shoud fix the issue. While trying to figure this out myself I also found #1206 which helped me fix the issue, but seems stale.
Please let me know if anything needs to change.
I've also added a space to the string formatting as this looks more in line with for example eslint_d output
> fix(builtins): add golangci_lint support for monorepos

- lua/null-ls/builtins/formatting/sqlfmt.lua
When using vim-dadbod-ui to write SQL queries, it creates the query files with no extension, but sets the SQL filetype for the buffer. These files currently will not format using sqlfmt, as sqlfmt ignores non-SQL file extensions when given a filename as input.
This patch switches the sqlfmt built-in formatter to using stdin instead of passing the file, which allows these files to be formatted correctly.
> Switch sqlfmt to using stdin instead of file

- doc/BUILTINS.md
- lua/null-ls/builtins/diagnostics/deno_lint.lua
Blazing fast linter for JavaScript and TypeScript written in Rust
```lua
local sources = { null_ls.builtins.diagnostics.deno_lint }
```
- Filetypes: `{ "javaScript", "typescript", "typescriptreact", "javascriptreact" }`
- Method: `diagnostics`
- Command: `deno`
- Args: `{ "lint", "--json", "-" }`
> feat: added deno_lint

- lua/null-ls/builtins/formatting/pyink.lua
`pyink` supports range formatting through the `--pyink-lines` option. It works if one decides to format a piece of code in visual mode with `vim.lsp.format()`. But for some reason `gqq` doesn't work. I checked and null-ls does set `formatexpr` as `vim.lsp.formatexpr()`. Did I miss something?
> feat: add pyink range formatting

- lua/null-ls/builtins/diagnostics/typos.lua
- test/spec/builtins/diagnostics_spec.lua
Current [PR](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/995) for [typos](https://github.com/crate-ci/typos) builtins is open for a long time. Raising this separate PR to at get the working diagnostics source merged.
> Added diagnosis builtin for typos-cli

- doc/BUILTINS.md
- lua/null-ls/builtins/formatting/fourmolu.lua
The old configuration was using `$FILEPATH` which appeared to be equal to an empty string at runtime.
If an empty string is passed to `fourmolu` for `--stdin-input-file`, then it can't find your `*.cabal` file and may choke because it's unaware of flags you enabled for the project. Example:
```
$ cat src/Forum/Webapi/Routes.hs  | fourmolu --stdin-input-file ""
Loaded config from: /home/david/Code/forum/fourmolu.yaml
<stdin>:1:1
The GHC parser (in Haddock mode) failed:
{ErrorWithoutFlag
Found `qualified' in postpositive position.
ErrorWithoutFlag
Found `qualified' in postpositive position.
ErrorWithoutFlag
Found `qualified' in postpositive position.
ErrorWithoutFlag
Found `qualified' in postpositive position.
ErrorWithoutFlag
Found `qualified' in postpositive position. }
```
Updating the …
> Change $FILEPATH to $FILENAME in the fourmolu configuration.

- lua/null-ls/builtins/formatting/blackd.lua
> feat: add blackd support
