jose-elias-alvarez/null-ls.nvim

lua/null-ls/formatting.lua, test/spec/e2e_spec.lua
While looking into the issue, I found [this PR](https://github.com/neovim/neovim/pull/14630) on the main Neovim repo by @folke, which solves the issue cleanly (in my opinion). This PR simply incorporates that code into null-ls.
=> feat(formatting): save buffer marks

lua/null-ls/builtins/formatting.lua
Do mind that these formatters should not be used concurrently. Using them
together will cause malformed files.
=> add builtin isort and black formatter

doc/BUILTINS.md, lua/null-ls/builtins/formatting.lua, lua/null-ls/config.lua, lua/null-ls/formatting.lua, lua/null-ls/helpers.lua, lua/null-ls/methods.lua, lua/null-ls/server.lua, lua/null-ls/utils.lua, test/spec/formatting_spec.lua, test/spec/helpers_spec.lua
Adds support for `textDocument/rangeFormatting`.
Example plugin that uses this feature:
- https://github.com/MunifTanjim/prettier.nvim
---
resolves #22
=> Support textDocument/rangeFormatting

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics.lua
=> feat: add hadolint diagnostics

lua/null-ls/builtins/diagnostics.lua
[![asciicast](https://asciinema.org/a/ASx3KjSZVoKoOBMMjttCk0XJo.svg)](https://asciinema.org/a/ASx3KjSZVoKoOBMMjttCk0XJo)
=> feat: add flake8 diagnostics

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics.lua
=> feat: add `misspell` diagnostics

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
I added issue forms for `bugs` and `features` in order to get more info and debug more easily.
Let me know if you want to add/change/remove anything.
I can also add it to [nvim-lsp-ts-utils](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils) if this looks good. 
You can preview how it works on the [fork](https://github.com/vuki656/null-ls.nvim/issues)
=> [Feature]: Add issue forms

lua/null-ls/builtins/formatting.lua
Context: https://github.com/neovim/nvim-lspconfig/pull/1009
=> [FIX]: add terraform ft, remove hcl

lua/null-ls/builtins/diagnostics.lua, lua/null-ls/diagnostics.lua, lua/null-ls/generators.lua, lua/null-ls/helpers.lua, test/spec/builtins/diagnostics_spec.lua, test/spec/e2e_spec.lua, test/spec/helpers_spec.lua
Hello :wave: 
I implemented helper functions to implement new diagnostic providers with more ease.
I also refactored the existing ones to showcase the added value.
<del>
I was unfortunately not able to test all linters, so if you could give me a hand on this that would be super helpful.
I tested:
- shellcheck
- selene
- eslint
- flake8
- misspell
- vint
- teal (unitary)
- write-good (unitary)
</del>
All linters are now unit-tested :tada: 
I didn't refactor the implementation for vale as I never managed to make it report something.
I hope you like it, tell me what you think.
=> [Feature] provide diagnostic helpers

lua/null-ls/builtins/diagnostics.lua
This will allow the user to define its own diagnostic attribute adapters like [here](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/59#issuecomment-888865823).
This should make the parser flexible enough to support any kind of edge case.
=> Allow user defined diagnostic attribute adapters.

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, README.md
- Added field for the stack trace
- Made repro, expected and actual fields required
- Added link to discussions
- Added guide on how to enable and use debug mode
=> Update issue templates

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics.lua, test/spec/builtins/diagnostics_spec.lua
=> [Feature] Add luacheck linter

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics.lua, lua/null-ls/builtins/formatting.lua
support svelte in prettier and ESLint
=> feat: add svelte in builtins format

lua/null-ls/builtins/diagnostics.lua, lua/null-ls/builtins/formatting.lua, lua/null-ls/config.lua
set value to clang_format (clang-format) filename argument
Refs #85
=> fix: clang-format filename argument

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics.lua
Adds pylint support.
Also an entry for flake8 in the docs, since I was there anyways.
=> Add pylint as a diagnostic for python

doc/BUILTINS.md, lua/null-ls/builtins/formatting.lua
Hi there,
<code>prisma-fmt</code> is a formatter dedicated for <code>prisma</code> scheme files
https://github.com/prisma/prisma-engines
=> feat: add prisma-fmt formatter

doc/BUILTINS.md, lua/null-ls/helpers.lua, test/spec/helpers_spec.lua
=> Extend buitin args with user provided ones

lua/null-ls/helpers.lua, test/spec/helpers_spec.lua
I overlooked this possibility :)
=> [Bugfix] Add missing check for nil args + tests

doc/BUILTINS.md
It's already supported, just wasn't in the list.
=> Mention shellcheck in BUILTINS.md

lua/null-ls/rpc.lua
=> Handle non-table request params

doc/BUILTINS.md, lua/null-ls/builtins/formatting.lua
[shellharden](https://github.com/anordal/shellharden) and [golines](https://pkg.go.dev/github.com/segmentio/golines) are awesome ! 
I've added them as formatting sources
=> Add `shellharden` & `golines` to formatting sources

lua/null-ls/generators.lua, test/spec/generators_spec.lua
Slightly overdue. Nothing major, since the usage here is pretty simple to begin with, but a nice improvement to ergonomics. Still need to fix unit tests.
=> refactor: migrate to plenary async v2

lua/null-ls/builtins/diagnostics.lua
https://github.com/jose-elias-alvarez/null-ls.nvim/issues/149
Similarly to https://github.com/dwb/neovim/commit/9794f6caef063ba1283bb728ac3befda477935f3
=> fix(builtin): pylint column off by one

lua/null-ls/helpers.lua, lua/null-ls/loop.lua, test/spec/helpers_spec.lua, test/spec/loop_spec.lua
=> Append filname to temp_file

lua/null-ls/loop.lua, test/spec/loop_spec.lua
This PR modifies `loop.temp_file` to use `uv.fs_mkstemp` when available, which should theoretically work on Windows (though we need a Windows user to actually test it). Also, when given an extension, the method now uses `uv.fs_rename` to rename the original temp file (instead of unlinking it). 
@meck Could you let me know if this PR works for you? And thank you for the suggestion to use `fs_rename`!
=> refactor(loop): prefer using fs_mkstemp and fs_rename

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics.lua
This introduce builtin diagnostic for [phpstan](https://github.com/phpstan/phpstan), a php static analyser.
=> feat: introduce phpstan php static analysis tool

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics.lua
This introduce builtin diagnostic for [psalm](https://psalm.dev), a php static analyser.
=> feat: introduce psalm php static analyser

lua/null-ls/utils.lua, test/spec/diagnostics_spec.lua, test/spec/e2e_spec.lua
=> fix: correctly wrap ranges according to lsp spec

doc/BUILTINS.md, lua/null-ls/builtins/formatting.lua
introduce [php-cs-fixer](https://github.com/FriendsOfPhp/PHP-CS-Fixer) formatter for php files
=> feat: introduce php-cs-fixer formatter

lua/null-ls/helpers.lua
=> fix diagnostics not reporting if multiple sources on the same file

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics.lua, test/spec/builtins/diagnostics_spec.lua
=> Fix shellcheck column range for tab indents

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics.lua, lua/null-ls/builtins/formatting.lua
This PR has the following:
* Adds "stylelint" diagnostics builtin
* Adds "stylelint" formatting builtin
* Updates documentation
=> Add "stylelint" diagnostics and formatter

lua/null-ls/builtins/diagnostics.lua
Missing `col` value, `vim.diagnostic.goto_next/prev()` have only moved cursor to the head of detected line.
With this commit, the functions will move cursor to the detected word position.
=> feat(builtin): make codespell diagnostics include columns

lua/null-ls/loop.lua
Noticed a couple issues when using the pylint builtin.
1. When pylint times out, `output_errors` gets assigned from `output`, this results in the `error in generator output: ...` error. Fixed this by not assigning error output on a timeout.
2. The exit code checking logic is broken. `local result = f and f() or default` does not work if `f` returns a boolean. Needs to be re-written using `if`.
=> fix issues with exit code handling

lua/null-ls/builtins/diagnostics.lua, lua/null-ls/builtins/formatting.lua, lua/null-ls/helpers.lua
=> feat: Add from_errorformat and qmllint/qmlformat sources

lua/null-ls/diff.lua, lua/null-ls/formatting.lua, lua/null-ls/helpers.lua, lua/null-ls/utils.lua, test/spec/diff_spec.lua, test/spec/formatting_spec.lua, test/spec/utils_spec.lua
Might fix #312. Needs tests if it does.
=> fix: check fileformat to determine newline char

doc/BUILTINS.md, lua/null-ls/builtins/completion/vsnip.lua
This adds a completion source [vim-vsnip](https://github.com/hrsh7th/vim-vsnip).
=> Completion source for vim-vsnip

doc/BUILTINS.md
Hello! This was recently changed
=> fix: update nvim-lspconfig link

doc/BUILTINS.md, lua/null-ls/builtins/code_actions/statix.lua, lua/null-ls/builtins/diagnostics/statix.lua
Statix changed it's default config again, but a stdin
has been added so we use this
=> Statix fix options

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics/cspell.lua
This PR adds [cspell](https://github.com/streetsidesoftware/cspell) as a diagnostics source.
=> feat(diagnostics): add cspell

lua/null-ls/builtins/formatting/nginx_beautifier.lua
Attempt to fix nginx-beautifier wrong output
=> fix(nginx_beautifier): wrong output

lua/null-ls/builtins/diagnostics/flake8.lua
Adds error message capture for some of the most popular flake8
extensions.
Closes #365
=> Additional message handlers for the flake8 diagnostic builtin

lua/null-ls/helpers.lua, lua/null-ls/init.lua, lua/null-ls/lspconfig.lua, lua/null-ls/rpc.lua, test/spec/lspconfig_spec.lua
Update to match the latest changes in `lspconfig` that were introduced in https://github.com/neovim/nvim-lspconfig/pull/1479
Fixes #378
=> fix(lspconfig): update the setup workflow

lua/null-ls/helpers.lua, lua/null-ls/init.lua, lua/null-ls/lspconfig.lua, lua/null-ls/rpc.lua, test/spec/lspconfig_spec.lua
Reverts jose-elias-alvarez/null-ls.nvim#379
=> Revert "fix(lspconfig): update the setup workflow"

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics/pylama.lua, test/spec/builtins/diagnostics_spec.lua
[Pylama](https://github.com/klen/pylama) is python code audit tool. It's like `flake8` but has some unique features. The integration supports pylama v8.1.4+
=> feat: add pylama

doc/BUILTINS.md, doc/HELPERS.md, doc/MAIN.md, lua/null-ls/builtins/_test/mock_multiple_file_diagnostics.lua, lua/null-ls/builtins/diagnostics/tsc.lua, lua/null-ls/diagnostics.lua, lua/null-ls/generators.lua, lua/null-ls/helpers.lua, test/spec/diagnostics_spec.lua, test/spec/e2e_spec.lua, test/spec/generators_spec.lua, test/spec/helpers_spec.lua
Closes #194.
While working on #351, I realized that a better way to support project diagnostics might be to allow ~~any~~ diagnostics sources to specify a filename / buffer number and use that to determine where to send diagnostics. This is a more logical approach for linters that run on save, such as the Go project linters we've recently added support for, and it removes the need for additional commands / special handling. **Update**: Sources must now use the `multiple_files` flag to signal that their results should apply to more than one file, but everything else worked out as planned.
~~It might still make sense to add a command that sends a synthetic notification to run project linters and open the quickfix list. The source API makes it easier to enable and disable sources, but …
=> feat(diagnostics): project diagnostics v2

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics/revive.lua, lua/null-ls/builtins/diagnostics/staticcheck.lua
Change to go linters as discussed.
=> feat: enable project-level diagnostics for revive, staticcheck

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics/cspell.lua
In order to include language specific words as well
=> feat: Send buffer type to cspell

doc/BUILTINS.md, lua/null-ls/builtins/formatting/brittany.lua
=> feat: brittany formatting source for haskell files

doc/BUILTINS.md
=> Fix: url for pylint in BUILTINS.md

doc/BUILTINS.md
Document the mypy builtin added in #325.
=> doc: Add entry to BUILTINS.md for mypy.

doc/BUILTINS.md, lua/null-ls/utils.lua, test/spec/utils_spec.lua
=> feat(utils): root_has_file accept multiple entries

lua/null-ls/client.lua
Resolves #436 as ease-of-use functionality
=> fix: client formatting disable through resolved_capabilities

doc/BUILTINS.md, lua/null-ls/builtins/formatting/latexindent.lua
latexindent formatting source for latex files. No issues are attached.
=> add(source): latexindent formatting source

lua/null-ls/helpers.lua
root_dir detection doesn't work with prefer_local/local_only is used
This fixes it.
=> fix: correctly read root_dir for prefer_local/local_only

doc/BUILTINS.md, lua/null-ls/builtins/_meta/diagnostics.lua, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/_meta/formatting.lua, lua/null-ls/builtins/diagnostics/jsonlint.lua, lua/null-ls/builtins/diagnostics/mdl.lua, lua/null-ls/builtins/diagnostics/standardjs.lua, lua/null-ls/builtins/formatting/prettier_standard.lua, test/spec/builtins/diagnostics_spec.lua
As requested in issues: #467 & #468
=> feat: jsonlint, mdl, standardjs & prettier-standard (WIP)

lua/null-ls/builtins/code_actions/eslint_d.lua
Also switches away from using cursor movement to do the position computation.
The issue repros with multi-line changes, like import reordering. As-is, for an input like:
```typescript
import b;
import a;
```
which should look like:
```typescript
import a;
import b;
```
applying the fix will incorrectly result in:
```typescript
import b;
import a;
import b;
```
=> Fix eslint_d code_actions fix range computation

doc/BUILTINS.md, lua/null-ls/builtins/formatting/buildifier.lua
Closes https://github.com/jose-elias-alvarez/null-ls.nvim/issues/496
=> Add buildifier to formatting built-ins

doc/BUILTINS.md
=> chore(docs): sync sqlformat change

doc/BUILTINS.md, lua/null-ls/builtins/formatting/fourmolu.lua
=> feat: fourmolu formatting source for haskell files

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics/vulture.lua
[Vulture](https://github.com/jendrikseipp/vulture) finds unused code in Python programs.
=> feat(diagnostics): add vulture

doc/BUILTINS.md, lua/null-ls/builtins/formatting/pg_format.lua
https://github.com/darold/pgFormatter is a nice formatter I've been using for pgsql. it also kinda works for mysql  
thanks!
=> feat(builtins): Add pg_format

lua/null-ls/generators.lua
* don't send progress message for `COMPLETION` sources. These are
typically called too often and are too fast for the progress to be
useful.
* send the progress report before calling the source so we can see
what source is running right now.
=> feat(progress): progress reporting tweaks

lua/null-ls/builtins/diagnostics/alex.lua, test/spec/builtins/diagnostics_spec.lua
I added a test, but I can't tell if the test is passing. This works when I take the same diagnostic and use it locally, but even if I make the test try to fail intentionally, it still give the same number of `Failed` tests.
=> feat: Add builtin for [Alex](https://alexjs.com/)

doc/BUILTINS.md, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/_meta/formatting.lua, lua/null-ls/builtins/formatting/protolint.lua
Adds [protolint](https://github.com/yoheimuta/protolint) formatter for `.proto` files.
Let me know if anything needs to be adjusted.
=> feat(builtin): Add protolint formatter

doc/BUILTINS.md, lua/null-ls/builtins/_meta/diagnostics.lua, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/diagnostics/curlylint.lua
I'm using this config locally since quite some time and thought it might benefit more people
=> feat(builtins): add curlylint diagnostics

doc/BUILTINS.md, lua/null-ls/builtins/_meta/diagnostics.lua, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/diagnostics/pydocstyle.lua
I'm using this config locally since quite some time and thought it might benefit more people
=> feat(builtins): add pydocstyle diagnostics

doc/BUILTINS.md, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/_meta/formatting.lua, lua/null-ls/builtins/formatting/standardjs.lua
I'm not sure I'm doing this exactly correctly (see #364 and #508) but this config seems to work for me.
=> Add standardjs formatter to the builtins

doc/BUILTINS.md, lua/null-ls/builtins/formatting/nixpkgs_fmt.lua
Another nix code formatter.
A formatter that respect the developer's expressivity.
=> feat: Add nixpkgs-fmt

doc/BUILTINS.md, lua/null-ls/builtins/_meta/diagnostics.lua, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/diagnostics/zsh.lua
=> Add zsh diagnostics builtin

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics/actionlint.lua
Add [actionlint](https://github.com/rhysd/actionlint) to diagnostic builtins
=> Add actionlint to diagnostics builtins

doc/BUILTINS.md, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/_meta/formatting.lua, lua/null-ls/builtins/formatting/remark.lua
This is a built-inification of another custom formatter which I use very regularly for formatting Markdown files. Let me know if anything else I need to do to merge :)
=> Remark formatter

lua/null-ls/info.lua
Let me know if anything needs to be changed! 
This is how it looks when not attached.
Closes #664
=> feat(info): enable info when not attached

lua/null-ls/builtins/formatting/djlint.lua
add [djlint](https://github.com/Riverside-Healthcare/djLint) to support django,jinja formatting.
=> add djlint support

lua/null-ls/builtins/diagnostics/pylama.lua, test/spec/builtins/diagnostics_spec.lua
This is for issue: https://github.com/jose-elias-alvarez/null-ls.nvim/issues/679
This is my first time doing a pull request for someone on github, and I'm also unfamiliar with using lua. Let me know if you have any problems with my process here.
I'm also not super sure on the approach I've taken to "solve" the issue here, but I suspect its "good enough". Let me know if you'd like me to try a different approach.
=> Handle pylama giving non-json outputs when the Python will not compile

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics/rpmspec.lua
This add diagnostics for RPM spec files.
=> feat(builtins): Add rpmspec diagnostics builtin

.github/workflows/default.yml, lua/null-ls/builtins/diagnostics/puppet_lint.lua
I was thinking about ways to get up-to-date versions of stylua, selene and neovim installed in CI, and could only think of Homebrew and Nix. I'm most familiar with Nix, so that's what I implemented here. Hope it's not too much voodoo. 🙃
=> feat: run selene and tests in CI

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics/pyproject_flake8.lua
See [pyproject-flake8](https://github.com/csachs/pyproject-flake8).
=> feat(builtins): add 'pyproject_flake8'

lua/null-ls/builtins/formatting/prettier.lua, lua/null-ls/builtins/formatting/prettier_d_slim.lua, lua/null-ls/builtins/formatting/prettierd.lua
=> Add handlebars prettier support

doc/BUILTINS.md, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/diagnostics/buildifier.lua
Closes https://github.com/jose-elias-alvarez/null-ls.nvim/issues/734
=> Add buildifier linter diagnostics

doc/BUILTINS.md, lua/null-ls/builtins/_meta/diagnostics.lua, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/diagnostics/haml_lint.lua
See https://github.com/sds/haml-lint
=> feat(builtins) add haml-lint diagnostics

doc/BUILTINS.md, lua/null-ls/builtins/_meta/diagnostics.lua, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/diagnostics/stylint.lua
An alternative to stylelint for the stylus preprocessor.
=> Add stylint diagnostics

doc/BUILTINS.md, lua/null-ls/builtins/_meta/diagnostics.lua, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/_meta/formatting.lua, lua/null-ls/builtins/diagnostics/tidy.lua, lua/null-ls/builtins/formatting/tidy.lua
This is the last one, I swear.
=> Add tidy diagnostics & formatting

lua/null-ls/builtins/diagnostics/twigcs.lua
Add a built-in to support [Twigcs](https://github.com/friendsoftwig/twigcs).
=> feat(diagnostics): add support for Twigcs

lua/null-ls/builtins/diagnostics/semgrep.lua
Adding support for SemGrep diagnostics.
https://semgrep.dev/
=>  diagnostics: add semgrep

doc/BUILTINS.md, lua/null-ls/builtins/_meta/diagnostics.lua, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/diagnostics/mlint.lua
Adding support for mlint. Added comments about why mlint requires "DIAGNOSTICS_ON_SAVE"
=>  feat(diagnostics): add support for mlint 

lua/null-ls/builtins/code_actions/shellcheck.lua
I have confirmed that this works as expected
ISSUES_FIXED: #768
=> fix(code_actions): search for first non-command line for disable pragma

lua/null-ls/builtins/diagnostics/erb_lint.lua, lua/null-ls/builtins/formatting/erb_lint.lua, test/spec/builtins/diagnostics_spec.lua
Adds erblint diagnostics and formatter.
=> feat: add erblint diagnostics and formatter

lua/null-ls/builtins/formatting/verible_verilog_format.lua
should pass formatting check now
=> add verible_verilog_format.lua

doc/BUILTIN_CONFIG.md, lua/null-ls/builtins/diagnostics/phpstan.lua, lua/null-ls/helpers/make_builtin.lua, test/spec/helpers/make_builtin_spec.lua
Unfortunately I was unable to reopen #799
Like discussed in the previous PR
- Added some docs
- Simplified phpcs code
=> Allow overriding to_temp_file

lua/null-ls/builtins/formatting/jq.lua
Written in C, so it's blazing fast
=> feat: add `jq` formatter for `json`

lua/null-ls/builtins/diagnostics/teal.lua, test/spec/builtins/diagnostics_spec.lua, test/spec/e2e_spec.lua
- support different severities
- don't show diagnostics for different files
- improve parsing of spans
=> feat(builtins): rewrite teal diagnostics

lua/null-ls/builtins/formatting/stylelint.lua
Null-ls was ignoring stylelint stderr
=> Fix (builtins): stylelint format from stderr

lua/null-ls/builtins/formatting/swiftformat.lua
=> fix(swiftformat): no metadata available

doc/BUILTINS.md, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/_meta/formatting.lua, lua/null-ls/builtins/formatting/mdformat.lua
[mdformat
documentation](https://mdformat.readthedocs.io/en/stable/index.html)
Signed-off-by: Vladislav Doster <mvdoster@gmail.com>
=> feat: add mdformat to built-in formatters

doc/BUILTINS.md, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/_meta/formatting.lua, lua/null-ls/builtins/formatting/zprint.lua
[zprint](https://github.com/kkinnear/zprint)
Signed-off-by: Uriel C. A. Fernandes <fernandes.uriel@gmail.com>
=> feat: add clojure formatter zprint to built-in formatters

lua/null-ls/builtins/diagnostics/cfn_lint.lua
- Added support for cfn-lint diagnostics for linting yaml & json cloudformation files.
=> feat: added cfn-lint diagnostics

lua/null-ls/builtins/formatting/sql_formatter.lua
sql-formatter seems to work decently well for SQL and is _much_ faster than sqlfluff for formatting.
=> Add sql-formatter

lua/null-ls/builtins/formatting/prettier.lua, lua/null-ls/builtins/formatting/prettier_d_slim.lua, lua/null-ls/builtins/formatting/prettier_standard.lua, lua/null-ls/builtins/formatting/prettierd.lua
similar to [fix: eslint cwd by hori\-ryota · Pull Request \#833 · jose\-elias\-alvarez/null\-ls\.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/833)
=> feat: define prettier cwd

lua/null-ls/builtins/diagnostics/actionlint.lua
add `runtime_condition` to actionlint with cache
resolves #804
resolves #776
=> feat: define actionlint runtime_condition

lua/null-ls/builtins/diagnostics/opacheck.lua, test/spec/builtins/diagnostics_spec.lua
=> feat(builtins): rego files diagnostics with opa check

doc/BUILTINS.md, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/_meta/formatting.lua, lua/null-ls/builtins/formatting/beautysh.lua
Signed-off-by: Vladislav Doster <mvdoster@gmail.com>
=> feat: beautysh formatter for bash, sh, and zsh files

.github/workflows/default.yml, .pre-commit-config.yaml, doc/BUILTINS.md, lua/null-ls/builtins/diagnostics/phpstan.lua, lua/null-ls/builtins/formatting/mdformat.lua, lua/null-ls/formatting.lua, lua/null-ls/helpers/command_resolver.lua, lua/null-ls/utils.lua, scripts/autogen.lua, test/spec/diagnostics_spec.lua
This PR does the following:
1. Format files with StyLua v14 (not a huge fan of the changes, to be honest, but better to stay up to date)
2. Pin the version of StyLua we use in CI
3. Upgrade the version of StyLua in our pre-commit hook (weirdly, this doesn't work for me locally, but I think it's a transient error)
4. Fix a couple of random formatting issues in built-in documentation
=> chore: fix formatting issues

doc/BUILTINS.md, lua/null-ls/builtins/formatting/pint.lua
[pint](https://github.com/laravel/pint) is a  php code formatter.
=> feat(builtins): add support for pint

lua/null-ls/builtins/formatting/csharpier.lua
[csharpier](https://csharpier.com/)
=> feat: Added csharpier formatter

doc/BUILTINS.md, lua/null-ls/builtins/formatting/blade_formatter.lua
An opinionated blade template formatter for Laravel that respects readability
=>  feat(builtins): add support for blade-formatter

doc/BUILTINS.md, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/_meta/formatting.lua, lua/null-ls/builtins/formatting/cbfmt.lua
Add support for https://github.com/lukas-reineke/cbfmt
=> feature: add cbfmt

doc/BUILTINS.md, doc/CONFIG.md, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/_meta/formatting.lua, lua/null-ls/builtins/formatting/goimports_reviser.lua
It's a similar tool to the goimports, but it works a bit better in some situations.
=> feature: added goimports_reviser formatting tool

lua/null-ls/builtins/formatting/ocdc.lua
This adds the [ocdc](https://github.com/mdwint/ocdc) formatter.
=> feat: add ocdc formatter

doc/BUILTINS.md, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/_meta/formatting.lua, lua/null-ls/builtins/formatting/npm_groovy_lint.lua
Signed-off-by: Vladislav Doster <mvdoster@gmail.com>
=> feat: add npm-groovy-lint formatter

lua/null-ls/builtins/diagnostics/pylint.lua
=> adjust pylint to use "long" human-readable names

lua/null-ls/builtins/formatting/yamlfmt.lua
Added yamlfmt: https://github.com/google/yamlfmt
=> Add yamlfmt: YAML formatter

lua/null-ls/builtins/diagnostics/todo_comments.lua
Refers to #686.
I've implemented diagnostics, but I have a question.  Is there a way to get keywords by configuration?  Or can it only be hard-coded?
=> feat: add todo-comments diagnostics

lua/null-ls/builtins/formatting/gersemi.lua
Refers to #847
```cmake
message(STATUS "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
```
```cmake
message(
STATUS
"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
)
```
=> feat(formatters): add gersemi

lua/null-ls/builtins/formatting/eslint.lua
=> fix(builtins): fix eslint formatter exit code check

scripts/minimal_init.lua
=> chore: fix remote plugin error in minimal init file

lua/null-ls/builtins/diagnostics/todo_comments.lua
=> fix(diagnostics): parse all file for todo-comments

lua/null-ls/builtins/code_actions/eslint.lua, lua/null-ls/builtins/diagnostics/eslint.lua, lua/null-ls/builtins/formatting/eslint.lua
ESLint now has a [new `eslint.config.js` configuration file](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new).
=> feat(builtins): support eslint.config.js

lua/null-ls/builtins/formatting/rego.lua
Simple formatter for rego files using `opa fmt`
=> feat(builtins): add rego formatter

doc/BUILTIN_CONFIG.md, doc/HELPERS.md, lua/null-ls/helpers/generator_factory.lua, test/spec/helpers/generator_factory_spec.lua
Closes: #1151.
I think this should be enough to make it work. I tested it and seems fine.
=> feat: allow functions to be pass to the `env` option.

lua/null-ls/builtins/diagnostics/flake8.lua, lua/null-ls/builtins/formatting/isort.lua
Signed-off-by: weiyang <weiyang.ones@gmail.com>
=> fix(builtins): add 'cwd' for flake8 and isort

lua/null-ls/builtins/code_actions/gitsigns.lua
=> feat: reset_hunk and stage_hunk support range

lua/null-ls/builtins/_meta/diagnostics.lua, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/diagnostics/mlint.lua
i'm not familiar with `lua` or 'null-ls`, i tried this, and it's worked for me,
=> mlint work fine for octave(the open source of matlab) too

lua/null-ls/builtins/diagnostics/cspell.lua
=> fix(builtins): handle cspell output w/o suggestions

lua/null-ls/builtins/diagnostics/checkstyle.lua, test/spec/builtins/diagnostics_spec.lua
=> feat: add checkstyle builtin

lua/null-ls/builtins/diagnostics/pmd.lua, test/spec/builtins/diagnostics_spec.lua
=> feat: add PMD as a builtin

lua/null-ls/builtins/diagnostics/djlint.lua
=> fix: include code in djlint diagnostics

lua/null-ls/builtins/diagnostics/pmd.lua, test/spec/builtins/diagnostics_spec.lua
This improves the handling of messages that PMD sends to stderr. It also ignores messages about the analysis cache.
Closes #1213.
=> feat(pmd): improve stderr message handling

lua/null-ls/builtins/formatting/xmlformat.lua
add support for [xmlformat](https://github.com/pamoller/xmlformatter)
=> feat: add xmlformat support

lua/null-ls/builtins/diagnostics/actionlint.lua
Actionlint is not automatically picking up config files when using the "pipe in" version to lint files.
This PR changes the behaviour to honor the config file.
It's my first bit of Lua and Vim development, so please don't hesitate to point our more idiomatic solutions
=> feat(actionlint): Use actionlint config file

lua/null-ls/builtins/formatting/ruff.lua
=> feat(ruff): add support for formatting

lua/null-ls/builtins/formatting/autoflake.lua
=> Add autoflake formatter

lua/null-ls/builtins/diagnostics/swiftlint.lua, lua/null-ls/builtins/formatting/swiftlint.lua
This PR adds support for swiftlint as diagnostics and formatting source.
Sorry for poor description, not sure how to properly describe this tiny feature 🙈
https://user-images.githubusercontent.com/2384454/207402202-e0f19862-bf65-4aab-97bb-67c857332549.mp4
In this video I use both `swiftlint` and `swiftformat` sources
=> feat: add `swiftlint` builtin diagnostics and formatting

lua/null-ls/builtins/formatting/standardts.lua
Hey @jose-elias-alvarez, 
Hope you are doing great. I have added `standardts` to the built-in. When you have time, please review this pr.
If there are some changes required, please leave a comment, so I can address it
Cheers,
Koen
=> feat: add `standardts` builtin formatting

lua/null-ls/builtins/code_actions/cspell.lua
My `lua` skills are as good as my tailoring...
Thanks to @peterfication for this comment: 
https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1154#issuecomment-1362590225
=> fix(builtins): cspell parse multiline jsons

lua/null-ls/builtins/completion/luasnip.lua
I did something stupid with Git and closed #1343. This is the same, but rebased to fix CI.
=> feat: include snip.id in LuaSnip

doc/BUILTINS.md, lua/null-ls/builtins/formatting/prettierd.lua
=>  feat(prettierd): add support for range formatting 

lua/null-ls/builtins/diagnostics/djlint.lua
=> Use stdin instead of saved file for djlint

lua/null-ls/builtins/diagnostics/textlint.lua, lua/null-ls/builtins/formatting/textlint.lua
* Add dynamic commands (see #1378).
* Fix a blank setting for filetypes.
* Add cwd setting.
Sorry. More fixes than I explained in the Issue.
=> Textlint dynamic command

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics/vacuum.lua
This PR adds support for diagnostics using Vacuum, a fast OpenAPI linter written in Go.
=> feat(builtins): add vacuum

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics/npm_groovy_lint.lua
Seems to be working well for me 
https://user-images.githubusercontent.com/36175703/221279057-84932431-f583-4712-a022-43819c99008b.mp4
Closes https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1121
=> Add diagnostic support for npm-groovy-lint

doc/BUILTINS.md, lua/null-ls/builtins/formatting/phpcsfixer.lua
Also submitted a [PR#1078](https://github.com/williamboman/mason.nvim/pull/1078) in the mason.nvim project
=> php-cs-fixer: use new PHP-CS-Fixer/PHP-CS-Fixer repo

lua/null-ls/builtins/code_actions/gomodifytags.lua
Closes https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1454.
=> fix gomodifytags treesitter get node call

doc/BUILTINS.md, lua/null-ls/builtins/diagnostics/markuplint.lua
Hi, thanks for the nice plugin!
This PR adds [markuplint](https://markuplint.dev/) to builtins/diagnostics.
Please review.
=> feat(builtins): add markuplint to diagnostics

lua/null-ls/builtins/formatting/sqlfmt.lua
`METHOD` should be `method`.
format should write to temp file
=> fix: sqlfmt method & args

lua/null-ls/builtins/diagnostics/spectral.lua
Validation error for spectral diagnostic
=> Fix spectral cannot be loaded

doc/BUILTINS.md, lua/null-ls/builtins/_meta/diagnostics.lua, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/diagnostics/reek.lua, test/spec/builtins/diagnostics_spec.lua
Adds [Reek](https://github.com/troessner/reek) code smell detector for Ruby.
=> feat(diagnostics): Add reek

doc/BUILTINS.md, lua/null-ls/builtins/_meta/code_actions.lua, lua/null-ls/builtins/code_actions/ts_node_action.lua
This PR adds ts-node-action as a builtin for code actions.
=> feat: add ts-node-action as a code_action builtin

doc/MAIN.md
Would like to add to **MAIN.md** readmefile, a new function in that was added in Dec 2022 based on the pull request to help others, so that they don't have to dig through past issues to find out.
=> update readme to include conditional function

lua/null-ls/builtins/diagnostics/saltlint.lua
=> feat(builtins): Add suppoort for salt-lint

lua/null-ls/builtins/code_actions/cspell.lua, lua/null-ls/builtins/diagnostics/cspell.lua
=> chore: add deprecation notes to CSpell sources

lua/null-ls/builtins/formatting/pyink.lua
Pying is a black fork that add a lot of useful features like doc format, allow define the number of identity spaces.
=> feat: add pyink code formatter

doc/BUILTINS.md, lua/null-ls/builtins/_meta/filetype_map.lua, lua/null-ls/builtins/_meta/formatting.lua, lua/null-ls/builtins/formatting/racket_fixw.lua
Copied structure from raco_fmt.lua
=> feat: Add racket_fixw for formatting Racket files

doc/BUILTINS.md, lua/null-ls/builtins/formatting/jsonnetfmt.lua
Adds a formatter for https://jsonnet.org/
=> feat(builtins): Add support for jsonnetfmt

doc/MAIN.md
=> fix(README): update CompletionList link

lua/null-ls/rpc.lua
=> Fix code_actions on neovim nightly (0.10.0)

lua/null-ls/builtins/diagnostics/textidote.lua
=> feat: add textidote support
